pub mod composite;
#[cfg(feature = "pi-agent")]
pub mod pi_agent;
#[cfg(feature = "pi-agent")]
pub mod pi_agent_mcp;
#[cfg(feature = "pi-agent")]
pub mod pi_agent_provider_registry;
pub mod remote_acp;
pub mod vibe_kanban;
