pub mod auth;
pub mod backend;
pub mod backend_execution_placement;
pub mod canvas;
pub mod capability;
pub mod companion;
pub mod context;
pub mod error;
pub mod extension_management;
pub mod extension_package;
pub mod extension_runtime;
pub mod hooks;
pub mod llm_provider;
pub mod mcp_preset;
pub mod mcp_relay_adapter;
pub mod permission;
pub mod platform_config;
pub mod project;
pub mod reconcile;
pub mod relay_connector;
pub mod repository_set;
pub mod routine;
pub mod runtime;
pub mod runtime_bridge;
pub mod runtime_gateway;
pub mod scheduling;
pub mod session;
pub mod shared_library;
pub mod skill;
pub mod skill_asset;
pub mod story;
pub mod task;
pub mod vfs;
pub mod workflow;
pub mod workspace;
pub mod workspace_module;

#[cfg(test)]
pub(crate) mod test_support;

pub use error::ApplicationError;
pub use task::lock as task_lock;
pub use task::service as task_service;
pub use task::view_projector as task_view_projector;
