// Generated by `cargo run -p agentdash-agent-runtime-contract --bin generate_agent_runtime_contracts`; do not edit.

import type {
  ManagedRuntimeCommandAvailability as ManagedRuntimeCommandAvailabilityWire,
  ManagedRuntimeContractSchema as ManagedRuntimeContractSchemaWire,
  ManagedRuntimeOperation as ManagedRuntimeOperationWire,
  ManagedRuntimeOperationReceipt as ManagedRuntimeOperationReceiptWire,
  ManagedRuntimeProjectionSchema as ManagedRuntimeProjectionSchemaWire,
  ManagedRuntimeSnapshot as ManagedRuntimeSnapshotWire,
  ManagedRuntimeSourceBindingEvidence as ManagedRuntimeSourceBindingEvidenceWire,
  RuntimeU64,
} from "./agent-runtime-contracts";

type DecodeRuntimeU64<T> =
  T extends RuntimeU64 ? bigint
    : T extends readonly (infer Item)[] ? DecodeRuntimeU64<Item>[]
      : T extends object ? { [Key in keyof T]: DecodeRuntimeU64<T[Key]> }
        : T;

export type ManagedRuntimeCommandAvailability =
  DecodeRuntimeU64<ManagedRuntimeCommandAvailabilityWire>;
export type ManagedRuntimeOperationReceipt =
  DecodeRuntimeU64<ManagedRuntimeOperationReceiptWire>;
export type ManagedRuntimeOperation = DecodeRuntimeU64<ManagedRuntimeOperationWire>;
export type ManagedRuntimeSnapshot = DecodeRuntimeU64<ManagedRuntimeSnapshotWire>;
export type ManagedRuntimeProjectionSchema = DecodeRuntimeU64<ManagedRuntimeProjectionSchemaWire>;
export type ManagedRuntimeContractSchema =
  DecodeRuntimeU64<ManagedRuntimeContractSchemaWire>;

const CANONICAL_U64 = /^(0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$/;
const U64_MAX = 18_446_744_073_709_551_615n;

export class ManagedRuntimeContractDecodeError extends Error {
  readonly fieldPath: string;
  readonly expected: string;

  constructor(
    fieldPath: string,
    expected = "canonical unsigned-decimal u64 string",
  ) {
    super(`${fieldPath}: expected ${expected}`);
    this.fieldPath = fieldPath;
    this.expected = expected;
  }
}

function record(value: unknown, path: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new ManagedRuntimeContractDecodeError(path, "object");
  }
  return value as Record<string, unknown>;
}

function array(value: unknown, path: string): unknown[] {
  if (!Array.isArray(value)) {
    throw new ManagedRuntimeContractDecodeError(path, "array");
  }
  return value;
}

function runtimeU64(value: unknown, path: string): bigint {
  if (typeof value !== "string" || !CANONICAL_U64.test(value)) {
    throw new ManagedRuntimeContractDecodeError(path);
  }
  const decoded = BigInt(value);
  if (decoded > U64_MAX) {
    throw new ManagedRuntimeContractDecodeError(path, "u64 range");
  }
  return decoded;
}

export function encodeRuntimeU64(value: bigint, path = "$"): RuntimeU64 {
  if (typeof value !== "bigint" || value < 0n || value > U64_MAX) {
    throw new ManagedRuntimeContractDecodeError(path, "u64 bigint");
  }
  return value.toString(10) as RuntimeU64;
}

function optionalRuntimeU64(value: unknown, path: string): bigint | null {
  return value === null ? null : runtimeU64(value, path);
}

function decodeSourceBinding(
  value: unknown,
  path: string,
): DecodeRuntimeU64<ManagedRuntimeSourceBindingEvidenceWire> {
  const source = record(value, path);
  return {
    ...(source as unknown as ManagedRuntimeSourceBindingEvidenceWire),
    committed_at_revision: runtimeU64(
      source.committed_at_revision,
      `${path}.committed_at_revision`,
    ),
    applied_surface_revision: runtimeU64(
      source.applied_surface_revision,
      `${path}.applied_surface_revision`,
    ),
    activated_at_revision: optionalRuntimeU64(
      source.activated_at_revision,
      `${path}.activated_at_revision`,
    ),
  } as DecodeRuntimeU64<ManagedRuntimeSourceBindingEvidenceWire>;
}

function encodeSourceBinding(
  source: DecodeRuntimeU64<ManagedRuntimeSourceBindingEvidenceWire>,
): ManagedRuntimeSourceBindingEvidenceWire {
  return {
    ...source,
    committed_at_revision: encodeRuntimeU64(source.committed_at_revision),
    applied_surface_revision: encodeRuntimeU64(source.applied_surface_revision),
    activated_at_revision:
      source.activated_at_revision === null
        ? null
        : encodeRuntimeU64(source.activated_at_revision),
  } as ManagedRuntimeSourceBindingEvidenceWire;
}

function decodeOperationEvidence(value: unknown, path: string): unknown {
  if (value === null) return null;
  const evidence = record(value, path);
  switch (evidence.kind) {
    case "create":
    case "resume":
    case "activate":
      return {
        ...evidence,
        binding: decodeSourceBinding(evidence.binding, `${path}.binding`),
      };
    case "fork": {
      const progress = record(evidence.progress, `${path}.progress`);
      return {
        ...evidence,
        parent_binding: decodeSourceBinding(
          evidence.parent_binding,
          `${path}.parent_binding`,
        ),
        progress:
          progress.status === "provisioned"
            ? {
                ...progress,
                child_binding: decodeSourceBinding(
                  progress.child_binding,
                  `${path}.progress.child_binding`,
                ),
              }
            : progress,
      };
    }
    default:
      throw new ManagedRuntimeContractDecodeError(`${path}.kind`, "known operation evidence");
  }
}

function encodeOperationEvidence(value: unknown): unknown {
  if (value === null) return null;
  const evidence = value as Record<string, unknown>;
  switch (evidence.kind) {
    case "create":
    case "resume":
    case "activate":
      return {
        ...evidence,
        binding: encodeSourceBinding(
          evidence.binding as DecodeRuntimeU64<ManagedRuntimeSourceBindingEvidenceWire>,
        ),
      };
    case "fork": {
      const progress = evidence.progress as Record<string, unknown>;
      return {
        ...evidence,
        parent_binding: encodeSourceBinding(
          evidence.parent_binding as DecodeRuntimeU64<ManagedRuntimeSourceBindingEvidenceWire>,
        ),
        progress:
          progress.status === "provisioned"
            ? {
                ...progress,
                child_binding: encodeSourceBinding(
                  progress.child_binding as DecodeRuntimeU64<ManagedRuntimeSourceBindingEvidenceWire>,
                ),
              }
            : progress,
      };
    }
    default:
      return evidence;
  }
}

function decodeOperation(value: unknown, path: string): ManagedRuntimeOperation {
  const operation = record(value, path);
  return {
    ...(operation as unknown as ManagedRuntimeOperationWire),
    evidence: decodeOperationEvidence(operation.evidence, `${path}.evidence`),
  } as ManagedRuntimeOperation;
}

function encodeOperation(operation: ManagedRuntimeOperation): ManagedRuntimeOperationWire {
  return {
    ...operation,
    evidence: encodeOperationEvidence(operation.evidence),
  } as ManagedRuntimeOperationWire;
}

export function decodeManagedRuntimeOperationReceipt(
  value: unknown,
): ManagedRuntimeOperationReceipt {
  const receipt = record(value, "$");
  return {
    ...receipt,
    accepted_revision: runtimeU64(
      receipt.accepted_revision,
      "$.accepted_revision",
    ),
    evidence: decodeOperationEvidence(receipt.evidence, "$.evidence"),
  } as ManagedRuntimeOperationReceipt;
}

export function encodeManagedRuntimeOperationReceipt(
  receipt: ManagedRuntimeOperationReceipt,
): ManagedRuntimeOperationReceiptWire {
  return {
    ...receipt,
    accepted_revision: encodeRuntimeU64(
      receipt.accepted_revision,
      "$.accepted_revision",
    ),
    evidence: encodeOperationEvidence(receipt.evidence),
  } as ManagedRuntimeOperationReceiptWire;
}

function decodeAvailability(value: unknown, path: string): ManagedRuntimeCommandAvailability {
  const availability = record(value, path);
  const evidence = record(availability.evidence, `${path}.evidence`);
  return {
    ...(availability as unknown as ManagedRuntimeCommandAvailabilityWire),
    evidence: {
      ...evidence,
      decided_at_revision: runtimeU64(
        evidence.decided_at_revision,
        `${path}.evidence.decided_at_revision`,
      ),
      bound_surface_revision: optionalRuntimeU64(
        evidence.bound_surface_revision,
        `${path}.evidence.bound_surface_revision`,
      ),
      applied_surface_revision: optionalRuntimeU64(
        evidence.applied_surface_revision,
        `${path}.evidence.applied_surface_revision`,
      ),
    },
  } as ManagedRuntimeCommandAvailability;
}

function encodeAvailability(
  availability: ManagedRuntimeCommandAvailability,
): ManagedRuntimeCommandAvailabilityWire {
  return {
    ...availability,
    evidence: {
      ...availability.evidence,
      decided_at_revision: encodeRuntimeU64(availability.evidence.decided_at_revision),
      bound_surface_revision:
        availability.evidence.bound_surface_revision === null
          ? null
          : encodeRuntimeU64(availability.evidence.bound_surface_revision),
      applied_surface_revision:
        availability.evidence.applied_surface_revision === null
          ? null
          : encodeRuntimeU64(availability.evidence.applied_surface_revision),
    },
  } as ManagedRuntimeCommandAvailabilityWire;
}

function decodeAvailabilityMap(value: unknown, path: string) {
  const source = record(value, path);
  return Object.fromEntries(
    Object.entries(source).map(([key, entry]) => [
      key,
      decodeAvailability(entry, `${path}.${key}`),
    ]),
  ) as ManagedRuntimeSnapshot["command_availability"];
}

function encodeAvailabilityMap(
  source: ManagedRuntimeSnapshot["command_availability"],
): ManagedRuntimeSnapshotWire["command_availability"] {
  return Object.fromEntries(
    Object.entries(source).map(([key, entry]) => [
      key,
      encodeAvailability(entry as ManagedRuntimeCommandAvailability),
    ]),
  ) as ManagedRuntimeSnapshotWire["command_availability"];
}

function presentationContentBlock(value: unknown, path: string): unknown {
  const block = record(value, path);
  switch (block.kind) {
    case "text":
    case "image":
    case "local_resource":
    case "resource_link":
    case "skill_reference":
    case "mention":
    case "structured":
      return block;
    default:
      throw new ManagedRuntimeContractDecodeError(
        `${path}.kind`,
        "known presentation content block",
      );
  }
}

function presentationContent(
  value: unknown,
  path: string,
): unknown[] {
  return array(value, path).map((block, index) =>
    presentationContentBlock(block, `${path}[${index}]`)
  );
}

function planStep(value: unknown, path: string): unknown {
  const step = record(value, path);
  switch (step.status) {
    case "pending":
    case "in_progress":
    case "completed":
    case "failed":
      return step;
    default:
      throw new ManagedRuntimeContractDecodeError(
        `${path}.status`,
        "known plan step status",
      );
  }
}

function planSteps(value: unknown, path: string): unknown[] {
  return array(value, path).map((step, index) =>
    planStep(step, `${path}[${index}]`)
  );
}

function commandOutput(value: unknown, path: string): unknown {
  const output = record(value, path);
  switch (output.stream) {
    case "stdout":
    case "stderr":
    case "combined":
      return output;
    default:
      throw new ManagedRuntimeContractDecodeError(
        `${path}.stream`,
        "known command output stream",
      );
  }
}

function commandOutputs(value: unknown, path: string): unknown[] {
  return array(value, path).map((output, index) =>
    commandOutput(output, `${path}[${index}]`)
  );
}

function filePatch(value: unknown, path: string): unknown {
  const patch = record(value, path);
  switch (patch.change_kind) {
    case "add":
    case "update":
    case "delete":
    case "move":
      return patch;
    default:
      throw new ManagedRuntimeContractDecodeError(
        `${path}.change_kind`,
        "known file change kind",
      );
  }
}

function filePatches(value: unknown, path: string): unknown[] {
  return array(value, path).map((patch, index) =>
    filePatch(patch, `${path}[${index}]`)
  );
}

function fileSearchMode(value: unknown, path: string): unknown {
  switch (value) {
    case "grep":
    case "glob":
      return value;
    default:
      throw new ManagedRuntimeContractDecodeError(path, "known file search mode");
  }
}

function transformItemBody(
  value: unknown,
  path: string,
  direction: "decode" | "encode",
): unknown {
  const body = record(value, path);
  switch (body.kind) {
    case "user_message":
    case "hook_prompt":
    case "agent_message":
    case "file_read":
      return {
        ...body,
        content: presentationContent(body.content, `${path}.content`),
      };
    case "reasoning":
      return {
        ...body,
        summary: presentationContent(body.summary, `${path}.summary`),
        content: presentationContent(body.content, `${path}.content`),
      };
    case "plan":
      return {
        ...body,
        steps: planSteps(body.steps, `${path}.steps`),
      };
    case "command_execution":
      return {
        ...body,
        output: commandOutputs(body.output, `${path}.output`),
      };
    case "file_change":
      return {
        ...body,
        changes: filePatches(body.changes, `${path}.changes`),
        output: presentationContent(body.output, `${path}.output`),
      };
    case "file_search":
      return {
        ...body,
        mode: fileSearchMode(body.mode, `${path}.mode`),
      };
    case "mcp_tool_call":
    case "dynamic_tool_call":
    case "generic_tool_activity":
      return {
        ...body,
        progress: presentationContent(body.progress, `${path}.progress`),
      };
    case "subagent_activity":
      return {
        ...body,
        result: presentationContent(body.result, `${path}.result`),
      };
    case "web_search":
      return {
        ...body,
        results: presentationContent(body.results, `${path}.results`),
      };
    case "image_generation":
      return {
        ...body,
        outputs: presentationContent(body.outputs, `${path}.outputs`),
      };
    case "sleep":
      return {
        ...body,
        duration_ms:
          direction === "decode"
            ? runtimeU64(body.duration_ms, `${path}.duration_ms`)
            : encodeRuntimeU64(body.duration_ms as bigint, `${path}.duration_ms`),
      };
    case "context_compaction":
      return {
        ...body,
        summary:
          body.summary === null
            ? null
            : presentationContent(body.summary, `${path}.summary`),
      };
    case "error":
      return {
        ...body,
        details:
          body.details === null
            ? null
            : presentationContent(body.details, `${path}.details`),
      };
    case "collaboration_tool_call":
    case "image_view":
    case "review":
    case "terminal_control":
      return body;
    default:
      throw new ManagedRuntimeContractDecodeError(
        `${path}.kind`,
        "known item body",
      );
  }
}

function decodeItemBody(value: unknown, path: string): unknown {
  return transformItemBody(value, path, "decode");
}

function encodeItemBody(value: unknown, path: string): unknown {
  return transformItemBody(value, path, "encode");
}

function decodeItemPresentation(value: unknown, path: string): unknown {
  const presentation = record(value, path);
  const terminal =
    presentation.terminal === null
      ? null
      : (() => {
          const evidence = record(presentation.terminal, `${path}.terminal`);
          switch (evidence.outcome) {
            case "completed":
            case "failed":
            case "interrupted":
            case "lost":
              break;
            default:
              throw new ManagedRuntimeContractDecodeError(
                `${path}.terminal.outcome`,
                "known terminal outcome",
              );
          }
          return {
            ...evidence,
            completed_at_ms: optionalRuntimeU64(
              evidence.completed_at_ms,
              `${path}.terminal.completed_at_ms`,
            ),
            duration_ms: optionalRuntimeU64(
              evidence.duration_ms,
              `${path}.terminal.duration_ms`,
            ),
          };
        })();
  return {
    ...presentation,
    body: decodeItemBody(presentation.body, `${path}.body`),
    started_at_ms: optionalRuntimeU64(
      presentation.started_at_ms,
      `${path}.started_at_ms`,
    ),
    updated_at_ms: optionalRuntimeU64(
      presentation.updated_at_ms,
      `${path}.updated_at_ms`,
    ),
    terminal,
  };
}

function encodeItemPresentation(value: unknown, path: string): unknown {
  const presentation = record(value, path);
  const terminal =
    presentation.terminal === null
      ? null
      : (() => {
          const evidence = record(presentation.terminal, `${path}.terminal`);
          switch (evidence.outcome) {
            case "completed":
            case "failed":
            case "interrupted":
            case "lost":
              break;
            default:
              throw new ManagedRuntimeContractDecodeError(
                `${path}.terminal.outcome`,
                "known terminal outcome",
              );
          }
          return {
            ...evidence,
            completed_at_ms:
              evidence.completed_at_ms === null
                ? null
                : encodeRuntimeU64(
                    evidence.completed_at_ms as bigint,
                    `${path}.terminal.completed_at_ms`,
                  ),
            duration_ms:
              evidence.duration_ms === null
                ? null
                : encodeRuntimeU64(
                    evidence.duration_ms as bigint,
                    `${path}.terminal.duration_ms`,
                  ),
          };
        })();
  return {
    ...presentation,
    body: encodeItemBody(presentation.body, `${path}.body`),
    started_at_ms:
      presentation.started_at_ms === null
        ? null
        : encodeRuntimeU64(
            presentation.started_at_ms as bigint,
            `${path}.started_at_ms`,
          ),
    updated_at_ms:
      presentation.updated_at_ms === null
        ? null
        : encodeRuntimeU64(
            presentation.updated_at_ms as bigint,
            `${path}.updated_at_ms`,
          ),
    terminal,
  };
}

function decodeItem(value: unknown, path: string): unknown {
  const item = record(value, path);
  return {
    ...item,
    presentation: decodeItemPresentation(
      item.presentation,
      `${path}.presentation`,
    ),
  };
}

function encodeItem(value: unknown, path: string): unknown {
  const item = record(value, path);
  return {
    ...item,
    presentation: encodeItemPresentation(
      item.presentation,
      `${path}.presentation`,
    ),
  };
}

export function decodeManagedRuntimeSnapshot(value: unknown): ManagedRuntimeSnapshot {
  const snapshot = record(value, "$");
  const threadNameSource =
    snapshot.thread_name_source === null
      ? null
      : (() => {
          const source = record(snapshot.thread_name_source, "$.thread_name_source");
          return {
            ...source,
            observed_at_ms: runtimeU64(
              source.observed_at_ms,
              "$.thread_name_source.observed_at_ms",
            ),
          };
        })();
  return {
    ...(snapshot as unknown as ManagedRuntimeSnapshotWire),
    revision: runtimeU64(snapshot.revision, "$.revision"),
    captured_at_ms: runtimeU64(snapshot.captured_at_ms, "$.captured_at_ms"),
    thread_name_source: threadNameSource,
    items: array(snapshot.items, "$.items").map((item, index) =>
      decodeItem(item, `$.items[${index}]`)
    ),
    operations: array(snapshot.operations, "$.operations").map((operation, index) =>
      decodeOperation(operation, `$.operations[${index}]`)
    ),
    source_binding:
      snapshot.source_binding === null
        ? null
        : decodeSourceBinding(snapshot.source_binding, "$.source_binding"),
    command_availability: decodeAvailabilityMap(
      snapshot.command_availability,
      "$.command_availability",
    ),
  } as ManagedRuntimeSnapshot;
}

export function encodeManagedRuntimeSnapshot(
  snapshot: ManagedRuntimeSnapshot,
): ManagedRuntimeSnapshotWire {
  return {
    ...snapshot,
    revision: encodeRuntimeU64(snapshot.revision),
    captured_at_ms: encodeRuntimeU64(snapshot.captured_at_ms),
    thread_name_source:
      snapshot.thread_name_source === null
        ? null
        : {
            ...snapshot.thread_name_source,
            observed_at_ms: encodeRuntimeU64(snapshot.thread_name_source.observed_at_ms),
          },
    items: snapshot.items.map((item, index) =>
      encodeItem(item, `$.items[${index}]`)
    ) as ManagedRuntimeSnapshotWire["items"],
    operations: snapshot.operations.map(encodeOperation),
    source_binding:
      snapshot.source_binding === null
        ? null
        : encodeSourceBinding(snapshot.source_binding),
    command_availability: encodeAvailabilityMap(snapshot.command_availability),
  } as ManagedRuntimeSnapshotWire;
}

export function decodeManagedRuntimeProjectionSchema(
  value: unknown,
): ManagedRuntimeProjectionSchema {
  const root = record(value, "$");
  return { snapshot: decodeManagedRuntimeSnapshot(root.snapshot) };
}

export function encodeManagedRuntimeProjectionSchema(
  value: ManagedRuntimeProjectionSchema,
): ManagedRuntimeProjectionSchemaWire {
  return {
    snapshot: encodeManagedRuntimeSnapshot(value.snapshot),
  };
}

export function decodeManagedRuntimeContractSchema(
  value: unknown,
): ManagedRuntimeContractSchema {
  const root = record(value, "$");
  return {
    initial_context: record(root.initial_context, "$.initial_context"),
    interaction_response: record(
      root.interaction_response,
      "$.interaction_response",
    ),
    operation_receipt: decodeManagedRuntimeOperationReceipt(root.operation_receipt),
    snapshot: decodeManagedRuntimeSnapshot(root.snapshot),
  } as ManagedRuntimeContractSchema;
}

export function encodeManagedRuntimeContractSchema(
  value: ManagedRuntimeContractSchema,
): ManagedRuntimeContractSchemaWire {
  return {
    initial_context: value.initial_context,
    interaction_response: value.interaction_response,
    operation_receipt: encodeManagedRuntimeOperationReceipt(
      value.operation_receipt,
    ),
    snapshot: encodeManagedRuntimeSnapshot(value.snapshot),
  };
}

export function isManagedRuntimeSnapshot(value: unknown): value is ManagedRuntimeSnapshotWire {
  try {
    decodeManagedRuntimeSnapshot(value);
    return true;
  } catch {
    return false;
  }
}
