// Generated by `cargo run -p agentdash-agent-runtime-contract --bin generate_agent_runtime_contracts`; do not edit.

import type {
  AgentRuntimeCommandAvailability as AgentRuntimeCommandAvailabilityWire,
  AgentRuntimeContractSchema as AgentRuntimeContractSchemaWire,
  AgentRuntimeOperationReceipt as AgentRuntimeOperationReceiptWire,
  AgentRuntimeProjectionSchema as AgentRuntimeProjectionSchemaWire,
  AgentRuntimeUpdate as AgentRuntimeUpdateWire,
  AgentRuntimeView as AgentRuntimeViewWire,
  AgentRuntimeSourceBindingEvidence as AgentRuntimeSourceBindingEvidenceWire,
  RuntimeU64,
} from "./agent-runtime-contracts";

type DecodeRuntimeU64<T> =
  T extends RuntimeU64 ? bigint
    : T extends readonly (infer Item)[] ? DecodeRuntimeU64<Item>[]
      : T extends object ? { [Key in keyof T]: DecodeRuntimeU64<T[Key]> }
        : T;

export type AgentRuntimeCommandAvailability =
  DecodeRuntimeU64<AgentRuntimeCommandAvailabilityWire>;
export type AgentRuntimeOperationReceipt =
  DecodeRuntimeU64<AgentRuntimeOperationReceiptWire>;
export type AgentRuntimeView = DecodeRuntimeU64<AgentRuntimeViewWire>;
export type AgentRuntimeUpdate = DecodeRuntimeU64<AgentRuntimeUpdateWire>;
export type AgentRuntimeProjectionSchema = DecodeRuntimeU64<AgentRuntimeProjectionSchemaWire>;
export type AgentRuntimeContractSchema =
  DecodeRuntimeU64<AgentRuntimeContractSchemaWire>;

const CANONICAL_U64 = /^(0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$/;
const U64_MAX = 18_446_744_073_709_551_615n;

export class AgentRuntimeContractDecodeError extends Error {
  readonly fieldPath: string;
  readonly expected: string;

  constructor(
    fieldPath: string,
    expected = "canonical unsigned-decimal u64 string",
  ) {
    super(`${fieldPath}: expected ${expected}`);
    this.fieldPath = fieldPath;
    this.expected = expected;
  }
}

function record(value: unknown, path: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new AgentRuntimeContractDecodeError(path, "object");
  }
  return value as Record<string, unknown>;
}

function array(value: unknown, path: string): unknown[] {
  if (!Array.isArray(value)) {
    throw new AgentRuntimeContractDecodeError(path, "array");
  }
  return value;
}

function runtimeU64(value: unknown, path: string): bigint {
  if (typeof value !== "string" || !CANONICAL_U64.test(value)) {
    throw new AgentRuntimeContractDecodeError(path);
  }
  const decoded = BigInt(value);
  if (decoded > U64_MAX) {
    throw new AgentRuntimeContractDecodeError(path, "u64 range");
  }
  return decoded;
}

export function encodeRuntimeU64(value: bigint, path = "$"): RuntimeU64 {
  if (typeof value !== "bigint" || value < 0n || value > U64_MAX) {
    throw new AgentRuntimeContractDecodeError(path, "u64 bigint");
  }
  return value.toString(10) as RuntimeU64;
}

function optionalRuntimeU64(value: unknown, path: string): bigint | null {
  return value === null ? null : runtimeU64(value, path);
}

function decodeSourceBinding(
  value: unknown,
  path: string,
): DecodeRuntimeU64<AgentRuntimeSourceBindingEvidenceWire> {
  const source = record(value, path);
  return {
    ...(source as unknown as AgentRuntimeSourceBindingEvidenceWire),
    committed_at_revision: runtimeU64(
      source.committed_at_revision,
      `${path}.committed_at_revision`,
    ),
    applied_surface_revision: runtimeU64(
      source.applied_surface_revision,
      `${path}.applied_surface_revision`,
    ),
    activated_at_revision: optionalRuntimeU64(
      source.activated_at_revision,
      `${path}.activated_at_revision`,
    ),
  } as DecodeRuntimeU64<AgentRuntimeSourceBindingEvidenceWire>;
}

function encodeSourceBinding(
  source: DecodeRuntimeU64<AgentRuntimeSourceBindingEvidenceWire>,
): AgentRuntimeSourceBindingEvidenceWire {
  return {
    ...source,
    committed_at_revision: encodeRuntimeU64(source.committed_at_revision),
    applied_surface_revision: encodeRuntimeU64(source.applied_surface_revision),
    activated_at_revision:
      source.activated_at_revision === null
        ? null
        : encodeRuntimeU64(source.activated_at_revision),
  } as AgentRuntimeSourceBindingEvidenceWire;
}

function decodeOperationEvidence(value: unknown, path: string): unknown {
  if (value === null) return null;
  const evidence = record(value, path);
  switch (evidence.kind) {
    case "create":
    case "resume":
    case "activate":
      return {
        ...evidence,
        binding: decodeSourceBinding(evidence.binding, `${path}.binding`),
      };
    case "fork": {
      const progress = record(evidence.progress, `${path}.progress`);
      return {
        ...evidence,
        parent_binding: decodeSourceBinding(
          evidence.parent_binding,
          `${path}.parent_binding`,
        ),
        progress:
          progress.status === "provisioned"
            ? {
                ...progress,
                child_binding: decodeSourceBinding(
                  progress.child_binding,
                  `${path}.progress.child_binding`,
                ),
              }
            : progress,
      };
    }
    default:
      throw new AgentRuntimeContractDecodeError(`${path}.kind`, "known operation evidence");
  }
}

function encodeOperationEvidence(value: unknown): unknown {
  if (value === null) return null;
  const evidence = value as Record<string, unknown>;
  switch (evidence.kind) {
    case "create":
    case "resume":
    case "activate":
      return {
        ...evidence,
        binding: encodeSourceBinding(
          evidence.binding as DecodeRuntimeU64<AgentRuntimeSourceBindingEvidenceWire>,
        ),
      };
    case "fork": {
      const progress = evidence.progress as Record<string, unknown>;
      return {
        ...evidence,
        parent_binding: encodeSourceBinding(
          evidence.parent_binding as DecodeRuntimeU64<AgentRuntimeSourceBindingEvidenceWire>,
        ),
        progress:
          progress.status === "provisioned"
            ? {
                ...progress,
                child_binding: encodeSourceBinding(
                  progress.child_binding as DecodeRuntimeU64<AgentRuntimeSourceBindingEvidenceWire>,
                ),
              }
            : progress,
      };
    }
    default:
      return evidence;
  }
}

export function decodeAgentRuntimeOperationReceipt(
  value: unknown,
): AgentRuntimeOperationReceipt {
  const receipt = record(value, "$");
  return {
    ...receipt,
    evidence: decodeOperationEvidence(receipt.evidence, "$.evidence"),
  } as AgentRuntimeOperationReceipt;
}

export function encodeAgentRuntimeOperationReceipt(
  receipt: AgentRuntimeOperationReceipt,
): AgentRuntimeOperationReceiptWire {
  return {
    ...receipt,
    evidence: encodeOperationEvidence(receipt.evidence),
  } as AgentRuntimeOperationReceiptWire;
}

function decodeAvailability(value: unknown, path: string): AgentRuntimeCommandAvailability {
  const availability = record(value, path);
  const evidence = record(availability.evidence, `${path}.evidence`);
  return {
    ...(availability as unknown as AgentRuntimeCommandAvailabilityWire),
    evidence: {
      ...evidence,
      expected_view_revision: optionalRuntimeU64(
        evidence.expected_view_revision,
        `${path}.evidence.expected_view_revision`,
      ),
      bound_surface_revision: optionalRuntimeU64(
        evidence.bound_surface_revision,
        `${path}.evidence.bound_surface_revision`,
      ),
      applied_surface_revision: optionalRuntimeU64(
        evidence.applied_surface_revision,
        `${path}.evidence.applied_surface_revision`,
      ),
    },
  } as AgentRuntimeCommandAvailability;
}

function encodeAvailability(
  availability: AgentRuntimeCommandAvailability,
): AgentRuntimeCommandAvailabilityWire {
  return {
    ...availability,
    evidence: {
      ...availability.evidence,
      expected_view_revision:
        availability.evidence.expected_view_revision === null
          ? null
          : encodeRuntimeU64(availability.evidence.expected_view_revision),
      bound_surface_revision:
        availability.evidence.bound_surface_revision === null
          ? null
          : encodeRuntimeU64(availability.evidence.bound_surface_revision),
      applied_surface_revision:
        availability.evidence.applied_surface_revision === null
          ? null
          : encodeRuntimeU64(availability.evidence.applied_surface_revision),
    },
  } as AgentRuntimeCommandAvailabilityWire;
}

function decodeAvailabilityMap(value: unknown, path: string) {
  const source = record(value, path);
  return Object.fromEntries(
    Object.entries(source).map(([key, entry]) => [
      key,
      decodeAvailability(entry, `${path}.${key}`),
    ]),
  ) as AgentRuntimeView["command_availability"];
}

function encodeAvailabilityMap(
  source: AgentRuntimeView["command_availability"],
): AgentRuntimeViewWire["command_availability"] {
  return Object.fromEntries(
    Object.entries(source).map(([key, entry]) => [
      key,
      encodeAvailability(entry as AgentRuntimeCommandAvailability),
    ]),
  ) as AgentRuntimeViewWire["command_availability"];
}

function decodeExecution(
  value: unknown,
  path: string,
): AgentRuntimeView["execution"] {
  const execution = record(value, path);
  const activeTurn = execution.active_turn === null
    ? null
    : (() => {
        const turn = record(execution.active_turn, `${path}.active_turn`);
        return {
          ...turn,
          started_at_ms: runtimeU64(
            turn.started_at_ms,
            `${path}.active_turn.started_at_ms`,
          ),
        };
      })();
  const queuedCompaction = execution.queued_compaction === null
    ? null
    : (() => {
        const queued = record(
          execution.queued_compaction,
          `${path}.queued_compaction`,
        );
        return {
          ...queued,
          queued_at_ms: runtimeU64(
            queued.queued_at_ms,
            `${path}.queued_compaction.queued_at_ms`,
          ),
        };
      })();
  const lastCompactionOutcome = execution.last_compaction_outcome === null
    ? null
    : (() => {
        const outcome = record(
          execution.last_compaction_outcome,
          `${path}.last_compaction_outcome`,
        );
        return {
          ...outcome,
          completed_at_ms: runtimeU64(
            outcome.completed_at_ms,
            `${path}.last_compaction_outcome.completed_at_ms`,
          ),
        };
      })();
  return {
    ...(execution as unknown as AgentRuntimeViewWire["execution"]),
    active_turn: activeTurn,
    queued_compaction: queuedCompaction,
    last_compaction_outcome: lastCompactionOutcome,
  } as AgentRuntimeView["execution"];
}

function encodeExecution(
  execution: AgentRuntimeView["execution"],
): AgentRuntimeViewWire["execution"] {
  return {
    ...execution,
    active_turn: execution.active_turn === null
      ? null
      : {
          ...execution.active_turn,
          started_at_ms: encodeRuntimeU64(execution.active_turn.started_at_ms),
        },
    queued_compaction: execution.queued_compaction === null
      ? null
      : {
          ...execution.queued_compaction,
          queued_at_ms: encodeRuntimeU64(
            execution.queued_compaction.queued_at_ms,
          ),
        },
    last_compaction_outcome: execution.last_compaction_outcome === null
      ? null
      : {
          ...execution.last_compaction_outcome,
          completed_at_ms: encodeRuntimeU64(
            execution.last_compaction_outcome.completed_at_ms,
          ),
        },
  };
}

export function decodeAgentRuntimeView(value: unknown): AgentRuntimeView {
  const view = record(value, "$");
  const context = record(view.context, "$.context");
  const threadNameSource =
    view.thread_name_source === null
      ? null
      : (() => {
          const source = record(view.thread_name_source, "$.thread_name_source");
          return {
            ...source,
            observed_at_ms: runtimeU64(
              source.observed_at_ms,
              "$.thread_name_source.observed_at_ms",
            ),
          };
        })();
  return {
    ...(view as unknown as AgentRuntimeViewWire),
    view_revision: runtimeU64(view.view_revision, "$.view_revision"),
    captured_at_ms: runtimeU64(view.captured_at_ms, "$.captured_at_ms"),
    execution: decodeExecution(view.execution, "$.execution"),
    context: {
      ...context,
      snapshot_revision: runtimeU64(
        context.snapshot_revision,
        "$.context.snapshot_revision",
      ),
    },
    thread_name_source: threadNameSource,
    source_binding:
      view.source_binding === null
        ? null
        : decodeSourceBinding(view.source_binding, "$.source_binding"),
    command_availability: decodeAvailabilityMap(
      view.command_availability,
      "$.command_availability",
    ),
  } as AgentRuntimeView;
}

export function encodeAgentRuntimeView(
  view: AgentRuntimeView,
): AgentRuntimeViewWire {
  return {
    ...view,
    view_revision: encodeRuntimeU64(view.view_revision),
    captured_at_ms: encodeRuntimeU64(view.captured_at_ms),
    execution: encodeExecution(view.execution),
    context: {
      ...view.context,
      snapshot_revision: encodeRuntimeU64(view.context.snapshot_revision),
    },
    thread_name_source:
      view.thread_name_source === null
        ? null
        : {
            ...view.thread_name_source,
            observed_at_ms: encodeRuntimeU64(view.thread_name_source.observed_at_ms),
          },
    source_binding:
      view.source_binding === null
        ? null
        : encodeSourceBinding(view.source_binding),
    command_availability: encodeAvailabilityMap(view.command_availability),
  } as AgentRuntimeViewWire;
}

export function decodeAgentRuntimeUpdate(value: unknown): AgentRuntimeUpdate {
  const update = record(value, "$");
  const context = record(update.context, "$.context");
  return {
    ...(update as unknown as AgentRuntimeUpdateWire),
    lane_sequence: runtimeU64(update.lane_sequence, "$.lane_sequence"),
    view_revision: runtimeU64(update.view_revision, "$.view_revision"),
    execution: decodeExecution(update.execution, "$.execution"),
    context: {
      ...context,
      snapshot_revision: runtimeU64(
        context.snapshot_revision,
        "$.context.snapshot_revision",
      ),
    },
    command_availability: decodeAvailabilityMap(
      update.command_availability,
      "$.command_availability",
    ),
    presentations: array(update.presentations, "$.presentations"),
  } as AgentRuntimeUpdate;
}

export function encodeAgentRuntimeUpdate(
  update: AgentRuntimeUpdate,
): AgentRuntimeUpdateWire {
  return {
    ...update,
    lane_sequence: encodeRuntimeU64(update.lane_sequence),
    view_revision: encodeRuntimeU64(update.view_revision),
    execution: encodeExecution(update.execution),
    context: {
      ...update.context,
      snapshot_revision: encodeRuntimeU64(update.context.snapshot_revision),
    },
    command_availability: encodeAvailabilityMap(update.command_availability),
  } as AgentRuntimeUpdateWire;
}

export function decodeAgentRuntimeProjectionSchema(
  value: unknown,
): AgentRuntimeProjectionSchema {
  const root = record(value, "$");
  return {
    view: decodeAgentRuntimeView(root.view),
    update: decodeAgentRuntimeUpdate(root.update),
  };
}

export function encodeAgentRuntimeProjectionSchema(
  value: AgentRuntimeProjectionSchema,
): AgentRuntimeProjectionSchemaWire {
  return {
    view: encodeAgentRuntimeView(value.view),
    update: encodeAgentRuntimeUpdate(value.update),
  };
}

export function decodeAgentRuntimeContractSchema(
  value: unknown,
): AgentRuntimeContractSchema {
  const root = record(value, "$");
  return {
    initial_context: record(root.initial_context, "$.initial_context"),
    interaction_response: record(
      root.interaction_response,
      "$.interaction_response",
    ),
    operation_receipt: decodeAgentRuntimeOperationReceipt(root.operation_receipt),
    view: decodeAgentRuntimeView(root.view),
  } as AgentRuntimeContractSchema;
}

export function encodeAgentRuntimeContractSchema(
  value: AgentRuntimeContractSchema,
): AgentRuntimeContractSchemaWire {
  return {
    initial_context: value.initial_context,
    interaction_response: value.interaction_response,
    operation_receipt: encodeAgentRuntimeOperationReceipt(
      value.operation_receipt,
    ),
    view: encodeAgentRuntimeView(value.view),
  };
}

export function isAgentRuntimeView(value: unknown): value is AgentRuntimeViewWire {
  try {
    decodeAgentRuntimeView(value);
    return true;
  } catch {
    return false;
  }
}
