use std::collections::{BTreeMap, BTreeSet};

use serde::Serialize;
use serde_json::Value;
use sha2::{Digest, Sha256};

#[derive(Debug, Clone, Copy)]
pub struct CodecRoot {
    pub type_name: &'static str,
    pub function_stem: &'static str,
}

#[derive(Debug, Clone, Copy)]
pub struct CodecModuleConfig<'a> {
    pub generated_by: &'a str,
    pub contract_import: &'a str,
    pub scalar_type: &'a str,
    pub decoded_type: &'a str,
    pub error_type: &'a str,
    pub decode_scalar: &'a str,
    pub encode_scalar: &'a str,
    pub roots: &'a [CodecRoot],
    pub type_guard: Option<(&'a str, &'a str)>,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum EncodingPlan {
    Identity,
    Scalar,
    Ref {
        name: String,
    },
    Nullable {
        inner: Box<EncodingPlan>,
    },
    Object {
        fields: BTreeMap<String, EncodingField>,
        #[serde(skip_serializing_if = "Option::is_none")]
        additional: Option<Box<EncodingPlan>>,
    },
    Array {
        items: Box<EncodingPlan>,
    },
    Union {
        variants: Vec<EncodingVariant>,
    },
    Sequence {
        items: Vec<EncodingPlan>,
    },
}

#[derive(Debug, Clone, PartialEq, Serialize)]
struct EncodingField {
    required: bool,
    plan: EncodingPlan,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
struct EncodingVariant {
    guards: BTreeMap<String, Value>,
    plan: EncodingPlan,
}

pub fn generate_codec_module(schema: &Value, config: CodecModuleConfig<'_>) -> String {
    let definitions = schema
        .get("$defs")
        .and_then(Value::as_object)
        .expect("contract schema must expose $defs");
    let mut plans = BTreeMap::new();
    for root in config.roots {
        let root_schema = definitions
            .get(root.type_name)
            .or_else(|| {
                (schema.get("title").and_then(Value::as_str) == Some(root.type_name))
                    .then_some(schema)
            })
            .unwrap_or_else(|| panic!("schema misses codec root {}", root.type_name));
        let plan = plan_for(
            root_schema,
            definitions,
            config.scalar_type,
            &mut Vec::new(),
        )
        .unwrap_or(EncodingPlan::Identity);
        plans.insert(root.type_name, plan);
    }
    let (plans, definitions) = deduplicate_plans(plans);
    let plan_json = serde_json::to_string_pretty(&plans).expect("serialize encoding plan");
    let definitions_json =
        serde_json::to_string_pretty(&definitions).expect("serialize encoding definitions");

    let imports = config
        .roots
        .iter()
        .map(|root| root.type_name)
        .chain(std::iter::once(config.scalar_type))
        .collect::<BTreeSet<_>>()
        .into_iter()
        .map(|name| format!("  {name} as {name}Wire,"))
        .collect::<Vec<_>>()
        .join("\n");
    let aliases = config
        .roots
        .iter()
        .map(|root| {
            format!(
                "export type {name} = {decoded}<{name}Wire>;",
                name = root.type_name,
                decoded = config.decoded_type,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let functions = config
        .roots
        .iter()
        .map(|root| {
            format!(
                r#"export function decode{stem}(value: unknown): {name} {{
  return transformEncoding(value, ENCODING_PLANS.{name}, "$", "decode") as {name};
}}

export function encode{stem}(value: {name}): {name}Wire {{
  return transformEncoding(value, ENCODING_PLANS.{name}, "$", "encode") as {name}Wire;
}}"#,
                stem = root.function_stem,
                name = root.type_name,
            )
        })
        .collect::<Vec<_>>()
        .join("\n\n");
    let type_guard = config
        .type_guard
        .map(|(function_name, root_name)| {
            format!(
                r#"

export function {function_name}(value: unknown): value is {root_name}Wire {{
  try {{
    decode{root_name}(value);
    return true;
  }} catch {{
    return false;
  }}
}}"#
            )
        })
        .unwrap_or_default();

    format!(
        r#"// Generated by `{generated_by}`; do not edit.

import type {{
{imports}
}} from "{contract_import}";

export type {decoded}<T> =
  T extends {scalar}Wire ? bigint
    : T extends readonly (infer Item)[] ? {decoded}<Item>[]
      : T extends object ? {{ [Key in keyof T]: {decoded}<T[Key]> }}
        : T;

{aliases}

const CANONICAL_U64 = /^(0|[1-9][0-9]{{0,18}}|1[0-7][0-9]{{18}}|18[0-3][0-9]{{17}}|184[0-3][0-9]{{16}}|1844[0-5][0-9]{{15}}|18446[0-6][0-9]{{14}}|184467[0-3][0-9]{{13}}|1844674[0-3][0-9]{{12}}|184467440[0-6][0-9]{{10}}|1844674407[0-2][0-9]{{9}}|18446744073[0-6][0-9]{{8}}|1844674407370[0-8][0-9]{{6}}|18446744073709[0-4][0-9]{{5}}|184467440737095[0-4][0-9]{{4}}|18446744073709550[0-9]{{3}}|18446744073709551[0-5][0-9]{{2}}|1844674407370955160[0-9]{{1}}|1844674407370955161[0-4]|18446744073709551615)$/;
const U64_MAX = 18_446_744_073_709_551_615n;

export class {error_type} extends Error {{
  readonly fieldPath: string;
  readonly expected: string;

  constructor(fieldPath: string, expected = "canonical unsigned-decimal u64 string") {{
    super(`${{fieldPath}}: expected ${{expected}}`);
    this.fieldPath = fieldPath;
    this.expected = expected;
  }}
}}

export function {decode_scalar}(value: unknown, path = "$"): bigint {{
  if (typeof value !== "string" || !CANONICAL_U64.test(value)) {{
    throw new {error_type}(path);
  }}
  const decoded = BigInt(value);
  if (decoded > U64_MAX) {{
    throw new {error_type}(path, "u64 range");
  }}
  return decoded;
}}

export function {encode_scalar}(value: bigint, path = "$"): {scalar}Wire {{
  if (typeof value !== "bigint" || value < 0n || value > U64_MAX) {{
    throw new {error_type}(path, "u64 bigint");
  }}
  return value.toString(10) as {scalar}Wire;
}}

type Direction = "decode" | "encode";
type EncodingPlan =
  | {{ kind: "identity" }}
  | {{ kind: "scalar" }}
  | {{ kind: "ref"; name: string }}
  | {{ kind: "nullable"; inner: EncodingPlan }}
  | {{ kind: "object"; fields: Record<string, EncodingField>; additional?: EncodingPlan }}
  | {{ kind: "array"; items: EncodingPlan }}
  | {{ kind: "union"; variants: EncodingVariant[] }}
  | {{ kind: "sequence"; items: EncodingPlan[] }};
type EncodingField = {{ required: boolean; plan: EncodingPlan }};
type EncodingVariant = {{ guards: Record<string, unknown>; plan: EncodingPlan }};

const ENCODING_PLANS: Record<string, EncodingPlan> = {plan_json};
const ENCODING_DEFINITIONS: Record<string, EncodingPlan> = {definitions_json};

function object(value: unknown, path: string): Record<string, unknown> {{
  if (value === null || typeof value !== "object" || Array.isArray(value)) {{
    throw new {error_type}(path, "object");
  }}
  return value as Record<string, unknown>;
}}

function transformEncoding(
  value: unknown,
  plan: EncodingPlan,
  path: string,
  direction: Direction,
): unknown {{
  switch (plan.kind) {{
    case "identity":
      return value;
    case "scalar":
      return direction === "decode"
        ? {decode_scalar}(value, path)
        : {encode_scalar}(value as bigint, path);
    case "ref":
      return transformEncoding(value, ENCODING_DEFINITIONS[plan.name], path, direction);
    case "nullable":
      return value === null ? null : transformEncoding(value, plan.inner, path, direction);
    case "array":
      if (!Array.isArray(value)) throw new {error_type}(path, "array");
      return value.map((item, index) =>
        transformEncoding(item, plan.items, `${{path}}[${{index}}]`, direction)
      );
    case "object": {{
      const source = object(value, path);
      const result: Record<string, unknown> = {{ ...source }};
      for (const [fieldName, field] of Object.entries(plan.fields)) {{
        if (!(fieldName in source)) {{
          if (field.required) throw new {error_type}(`${{path}}.${{fieldName}}`, "required field");
          continue;
        }}
        result[fieldName] = transformEncoding(
          source[fieldName],
          field.plan,
          `${{path}}.${{fieldName}}`,
          direction,
        );
      }}
      if (plan.additional) {{
        for (const [fieldName, fieldValue] of Object.entries(source)) {{
          if (fieldName in plan.fields) continue;
          result[fieldName] = transformEncoding(
            fieldValue,
            plan.additional,
            `${{path}}.${{fieldName}}`,
            direction,
          );
        }}
      }}
      return result;
    }}
    case "union": {{
      const guarded = plan.variants.filter((variant) =>
        Object.entries(variant.guards).every(
          ([fieldName, expected]) =>
            value !== null
            && typeof value === "object"
            && !Array.isArray(value)
            && (value as Record<string, unknown>)[fieldName] === expected,
        )
      );
      const candidates = guarded.length > 0
        ? guarded
        : plan.variants.filter((variant) => Object.keys(variant.guards).length === 0);
      if (candidates.length === 0) return value;
      let lastError: unknown = null;
      for (const candidate of candidates) {{
        try {{
          return transformEncoding(value, candidate.plan, path, direction);
        }} catch (error) {{
          lastError = error;
        }}
      }}
      throw lastError;
    }}
    case "sequence":
      return plan.items.reduce(
        (current, item) => transformEncoding(current, item, path, direction),
        value,
      );
  }}
}}

{functions}{type_guard}
"#,
        generated_by = config.generated_by,
        imports = imports,
        contract_import = config.contract_import,
        decoded = config.decoded_type,
        scalar = config.scalar_type,
        aliases = aliases,
        error_type = config.error_type,
        decode_scalar = config.decode_scalar,
        encode_scalar = config.encode_scalar,
        plan_json = plan_json,
        definitions_json = definitions_json,
        functions = functions,
        type_guard = type_guard,
    )
}

fn plan_for(
    schema: &Value,
    definitions: &serde_json::Map<String, Value>,
    scalar_type: &str,
    stack: &mut Vec<String>,
) -> Option<EncodingPlan> {
    if is_scalar(schema, definitions, scalar_type, &mut BTreeSet::new()) {
        return Some(EncodingPlan::Scalar);
    }
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let name = reference.strip_prefix("#/$defs/")?;
        if stack.iter().any(|entry| entry == name) {
            return None;
        }
        stack.push(name.to_owned());
        let plan = definitions
            .get(name)
            .and_then(|target| plan_for(target, definitions, scalar_type, stack));
        stack.pop();
        return plan;
    }

    for union_key in ["oneOf", "anyOf"] {
        if let Some(variants) = schema.get(union_key).and_then(Value::as_array) {
            let nullable = variants.iter().any(is_null_schema);
            let mut plans = variants
                .iter()
                .filter(|variant| !is_null_schema(variant))
                .filter_map(|variant| {
                    plan_for(variant, definitions, scalar_type, stack).map(|plan| EncodingVariant {
                        guards: guards_for(variant, definitions),
                        plan,
                    })
                })
                .collect::<Vec<_>>();
            deduplicate_variants(&mut plans);
            let plan = match plans.len() {
                0 => None,
                1 if plans[0].guards.is_empty() => Some(plans.remove(0).plan),
                _ => Some(EncodingPlan::Union { variants: plans }),
            };
            return plan.map(|inner| {
                if nullable {
                    EncodingPlan::Nullable {
                        inner: Box::new(inner),
                    }
                } else {
                    inner
                }
            });
        }
    }

    if let Some(parts) = schema.get("allOf").and_then(Value::as_array) {
        let mut items = parts
            .iter()
            .filter_map(|part| plan_for(part, definitions, scalar_type, stack))
            .collect::<Vec<_>>();
        return match items.len() {
            0 => None,
            1 => Some(items.remove(0)),
            _ => Some(EncodingPlan::Sequence { items }),
        };
    }

    if schema.get("type").and_then(Value::as_str) == Some("array") {
        return schema
            .get("items")
            .and_then(|items| plan_for(items, definitions, scalar_type, stack))
            .map(|items| EncodingPlan::Array {
                items: Box::new(items),
            });
    }

    let properties = schema.get("properties").and_then(Value::as_object);
    let additional = schema
        .get("additionalProperties")
        .filter(|value| value.is_object())
        .and_then(|value| plan_for(value, definitions, scalar_type, stack))
        .map(Box::new);
    if properties.is_some() || additional.is_some() {
        let required = schema
            .get("required")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .filter_map(Value::as_str)
            .collect::<BTreeSet<_>>();
        let fields = properties
            .into_iter()
            .flatten()
            .filter_map(|(name, field_schema)| {
                plan_for(field_schema, definitions, scalar_type, stack).map(|plan| {
                    (
                        name.clone(),
                        EncodingField {
                            required: required.contains(name.as_str()),
                            plan,
                        },
                    )
                })
            })
            .collect::<BTreeMap<_, _>>();
        if fields.is_empty() && additional.is_none() {
            None
        } else {
            Some(EncodingPlan::Object { fields, additional })
        }
    } else {
        None
    }
}

fn is_scalar(
    schema: &Value,
    definitions: &serde_json::Map<String, Value>,
    scalar_type: &str,
    visited: &mut BTreeSet<String>,
) -> bool {
    let Some(reference) = schema.get("$ref").and_then(Value::as_str) else {
        return false;
    };
    let Some(name) = reference.strip_prefix("#/$defs/") else {
        return false;
    };
    if name == scalar_type {
        return true;
    }
    visited.insert(name.to_owned())
        && definitions
            .get(name)
            .is_some_and(|target| is_scalar(target, definitions, scalar_type, visited))
}

fn guards_for(
    schema: &Value,
    definitions: &serde_json::Map<String, Value>,
) -> BTreeMap<String, Value> {
    let resolved = schema
        .get("$ref")
        .and_then(Value::as_str)
        .and_then(|reference| reference.strip_prefix("#/$defs/"))
        .and_then(|name| definitions.get(name))
        .unwrap_or(schema);
    resolved
        .get("properties")
        .and_then(Value::as_object)
        .into_iter()
        .flatten()
        .filter_map(|(name, property)| {
            property
                .get("const")
                .cloned()
                .map(|value| (name.clone(), value))
        })
        .collect()
}

fn is_null_schema(schema: &Value) -> bool {
    schema.get("type").and_then(Value::as_str) == Some("null")
}

fn deduplicate_variants(variants: &mut Vec<EncodingVariant>) {
    let mut seen = BTreeSet::new();
    variants.retain(|variant| {
        seen.insert(serde_json::to_string(variant).expect("serialize encoding variant"))
    });
}

fn deduplicate_plans(
    plans: BTreeMap<&'static str, EncodingPlan>,
) -> (
    BTreeMap<&'static str, EncodingPlan>,
    BTreeMap<String, EncodingPlan>,
) {
    let mut occurrences = BTreeMap::<String, (usize, EncodingPlan)>::new();
    for plan in plans.values() {
        collect_subplans(plan, &mut occurrences);
    }
    let names = occurrences
        .iter()
        .filter(|(serialized, (count, plan))| {
            *count > 1
                && serialized.len() >= 160
                && !matches!(
                    plan,
                    EncodingPlan::Identity | EncodingPlan::Scalar | EncodingPlan::Ref { .. }
                )
        })
        .enumerate()
        .map(|(index, (serialized, _))| (serialized.clone(), format!("p{index:04}")))
        .collect::<BTreeMap<_, _>>();
    let rewritten_roots = plans
        .into_iter()
        .map(|(name, plan)| (name, rewrite_plan(&plan, &names, false)))
        .collect();
    let definitions = names
        .iter()
        .map(|(serialized, name)| {
            let plan = &occurrences
                .get(serialized)
                .expect("deduplicated plan source")
                .1;
            (name.clone(), rewrite_plan(plan, &names, true))
        })
        .collect();
    (rewritten_roots, definitions)
}

fn collect_subplans(
    plan: &EncodingPlan,
    occurrences: &mut BTreeMap<String, (usize, EncodingPlan)>,
) {
    let serialized = serde_json::to_string(plan).expect("serialize encoding subplan");
    occurrences
        .entry(serialized)
        .and_modify(|(count, _)| *count += 1)
        .or_insert_with(|| (1, plan.clone()));
    match plan {
        EncodingPlan::Nullable { inner } | EncodingPlan::Array { items: inner } => {
            collect_subplans(inner, occurrences);
        }
        EncodingPlan::Object { fields, additional } => {
            for field in fields.values() {
                collect_subplans(&field.plan, occurrences);
            }
            if let Some(additional) = additional {
                collect_subplans(additional, occurrences);
            }
        }
        EncodingPlan::Union { variants } => {
            for variant in variants {
                collect_subplans(&variant.plan, occurrences);
            }
        }
        EncodingPlan::Sequence { items } => {
            for item in items {
                collect_subplans(item, occurrences);
            }
        }
        EncodingPlan::Identity | EncodingPlan::Scalar | EncodingPlan::Ref { .. } => {}
    }
}

fn rewrite_plan(
    plan: &EncodingPlan,
    names: &BTreeMap<String, String>,
    preserve_root: bool,
) -> EncodingPlan {
    let serialized = serde_json::to_string(plan).expect("serialize encoding rewrite candidate");
    if !preserve_root && let Some(name) = names.get(&serialized) {
        return EncodingPlan::Ref { name: name.clone() };
    }
    match plan {
        EncodingPlan::Nullable { inner } => EncodingPlan::Nullable {
            inner: Box::new(rewrite_plan(inner, names, false)),
        },
        EncodingPlan::Object { fields, additional } => EncodingPlan::Object {
            fields: fields
                .iter()
                .map(|(name, field)| {
                    (
                        name.clone(),
                        EncodingField {
                            required: field.required,
                            plan: rewrite_plan(&field.plan, names, false),
                        },
                    )
                })
                .collect(),
            additional: additional
                .as_ref()
                .map(|plan| Box::new(rewrite_plan(plan, names, false))),
        },
        EncodingPlan::Array { items } => EncodingPlan::Array {
            items: Box::new(rewrite_plan(items, names, false)),
        },
        EncodingPlan::Union { variants } => EncodingPlan::Union {
            variants: variants
                .iter()
                .map(|variant| EncodingVariant {
                    guards: variant.guards.clone(),
                    plan: rewrite_plan(&variant.plan, names, false),
                })
                .collect(),
        },
        EncodingPlan::Sequence { items } => EncodingPlan::Sequence {
            items: items
                .iter()
                .map(|item| rewrite_plan(item, names, false))
                .collect(),
        },
        EncodingPlan::Identity | EncodingPlan::Scalar | EncodingPlan::Ref { .. } => plan.clone(),
    }
}

pub fn canonicalize_json(value: &mut Value) {
    match value {
        Value::Object(object) => {
            let mut entries = std::mem::take(object).into_iter().collect::<Vec<_>>();
            entries.sort_by(|left, right| left.0.cmp(&right.0));
            for (_, value) in &mut entries {
                canonicalize_json(value);
            }
            object.extend(entries);
        }
        Value::Array(values) => {
            for value in values {
                canonicalize_json(value);
            }
        }
        _ => {}
    }
}

pub fn generation_manifest(root: &str, input: &str, outputs: &[(&str, &str)]) -> String {
    let mut hasher = Sha256::new();
    for (name, contents) in outputs {
        hasher.update(name.as_bytes());
        hasher.update([0]);
        hasher.update(contents.as_bytes());
        hasher.update([0]);
    }
    format!(
        "{}\n",
        serde_json::to_string_pretty(&serde_json::json!({
            "root": root,
            "input": input,
            "outputs": outputs.iter().map(|(name, _)| *name).collect::<Vec<_>>(),
            "digest": format!("sha256:{:x}", hasher.finalize()),
        }))
        .expect("serialize generation manifest")
    )
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn discovers_scalar_through_object_array_map_optional_and_union_refs() {
        let schema = json!({
            "$defs": {
                "RuntimeU64": {"type": "string"},
                "Alias": {"$ref": "#/$defs/RuntimeU64"},
                "Root": {
                    "type": "object",
                    "required": ["direct", "items", "mapping", "choice"],
                    "properties": {
                        "direct": {"$ref": "#/$defs/Alias"},
                        "items": {"type": "array", "items": {"$ref": "#/$defs/Alias"}},
                        "mapping": {"type": "object", "additionalProperties": {"$ref": "#/$defs/Alias"}},
                        "optional": {"anyOf": [{"$ref": "#/$defs/Alias"}, {"type": "null"}]},
                        "choice": {"oneOf": [
                            {"type": "object", "properties": {
                                "kind": {"const": "value"},
                                "revision": {"$ref": "#/$defs/Alias"}
                            }},
                            {"type": "object", "properties": {"kind": {"const": "empty"}}}
                        ]}
                    }
                }
            }
        });
        let source = generate_codec_module(
            &schema,
            CodecModuleConfig {
                generated_by: "test",
                contract_import: "./contract",
                scalar_type: "RuntimeU64",
                decoded_type: "DecodeRuntimeU64",
                error_type: "DecodeError",
                decode_scalar: "decodeRuntimeU64",
                encode_scalar: "encodeRuntimeU64",
                roots: &[CodecRoot {
                    type_name: "Root",
                    function_stem: "Root",
                }],
                type_guard: None,
            },
        );

        for fragment in [
            "\"direct\"",
            "\"items\"",
            "\"mapping\"",
            "\"optional\"",
            "\"guards\"",
            "\"value\"",
        ] {
            assert!(source.contains(fragment), "missing {fragment}");
        }
    }

    #[test]
    fn canonical_json_sorts_objects_without_reordering_arrays() {
        let mut value = json!({"z": 1, "a": {"d": 2, "b": 1}, "items": ["z", "a"]});
        canonicalize_json(&mut value);
        assert_eq!(
            serde_json::to_string(&value).unwrap(),
            r#"{"a":{"b":1,"d":2},"items":["z","a"],"z":1}"#
        );
    }
}
