use std::{collections::BTreeSet, env, fs, path::Path};

use agentdash_agent_runtime_contract::encoding_codegen::{
    CodecModuleConfig, CodecRoot, canonicalize_json, generate_codec_module, generation_manifest,
};
use agentdash_agent_runtime_contract::{
    AgentHostCallbackError, AgentRuntimeContractSchema, AgentRuntimeProjectionSchema,
    AgentRuntimeSourceBindingEvidence, AgentServiceApiSchema, AgentServiceInstanceId,
    CompleteAgentLiveAttachmentId, RuntimeU64,
};
use schemars::schema_for;
use ts_rs::TS;

fn main() {
    let check = env::args().any(|argument| argument == "--check");
    ensure_no_implicit_bindings();
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let ts_path = root.join("packages/app-web/src/generated/agent-runtime-contracts.ts");
    let protocol_ts_path = root.join("packages/app-web/src/generated/backbone-protocol.ts");
    let codecs_path = root.join("packages/app-web/src/generated/agent-runtime-codecs.ts");
    let schema_path = root.join("schemas/agent-runtime-contract.schema.json");
    let manifest_path = root.join("schemas/agent-runtime-contract.manifest.json");
    let temp = tempfile::tempdir().expect("create generation directory");
    AgentRuntimeContractSchema::export_all_to(temp.path())
        .expect("export Agent Runtime contract types");
    AgentRuntimeProjectionSchema::export_all_to(temp.path())
        .expect("export Agent Runtime projection types");
    AgentServiceApiSchema::export_all_to(temp.path())
        .expect("export Complete Agent contract types");
    AgentServiceInstanceId::export_all_to(temp.path())
        .expect("export Complete Agent service identity");
    CompleteAgentLiveAttachmentId::export_all_to(temp.path())
        .expect("export Complete Agent live attachment identity");
    AgentHostCallbackError::export_all_to(temp.path())
        .expect("export Complete Agent host callback error");
    AgentRuntimeSourceBindingEvidence::export_all_to(temp.path())
        .expect("export Product Runtime source binding evidence");
    RuntimeU64::export_all_to(temp.path()).expect("export canonical Runtime u64 wire scalar");
    let mut declarations = Vec::new();
    collect_typescript(temp.path(), &mut declarations);
    let protocol_types = exported_type_names(&protocol_ts_path);
    declarations.retain(|declaration| {
        declaration_name(declaration).is_none_or(|name| !protocol_types.contains(name))
    });
    declarations.sort();
    ensure_required_declarations(&declarations, &required_runtime_type_names());
    let typescript = format!(
        "// Generated by `cargo run -p agentdash-agent-runtime-contract --bin generate_agent_runtime_contracts`; do not edit.\n\nimport type {{ CanonicalConversationRecord, ContextFrame, TurnStatus }} from \"./backbone-protocol\";\n\n{}\n",
        declarations.join("\n\n")
    );
    ensure_no_bigint(&typescript);
    let mut schema_value =
        serde_json::to_value(schema_for!(AgentRuntimeContractSchema)).expect("serialize schema");
    let projection_schema = serde_json::to_value(schema_for!(AgentRuntimeProjectionSchema))
        .expect("serialize projection schema");
    merge_schema_definitions(&mut schema_value, &projection_schema);
    let codecs = generate_codec_module(
        &schema_value,
        CodecModuleConfig {
            generated_by: "cargo run -p agentdash-agent-runtime-contract --bin generate_agent_runtime_contracts",
            contract_import: "./agent-runtime-contracts",
            scalar_type: "RuntimeU64",
            decoded_type: "DecodeRuntimeU64",
            error_type: "AgentRuntimeCodecError",
            decode_scalar: "decodeRuntimeU64",
            encode_scalar: "encodeRuntimeU64",
            roots: codec_roots(),
            type_guard: Some(("isAgentRuntimeView", "AgentRuntimeView")),
        },
    );
    canonicalize_json(&mut schema_value);
    let json_schema = format!(
        "{}\n",
        serde_json::to_string_pretty(&schema_value).expect("serialize canonical Runtime schema")
    );
    let manifest = generation_manifest(
        "AgentRuntimeContractSchema",
        "schemars::schema_for!(AgentRuntimeContractSchema) + RuntimeU64 encoding kind",
        &[
            ("agent-runtime-contracts.ts", &typescript),
            ("agent-runtime-codecs.ts", &codecs),
            ("agent-runtime-contract.schema.json", &json_schema),
        ],
    );
    check_or_write(&ts_path, &typescript, check);
    check_or_write(&codecs_path, &codecs, check);
    check_or_write(&schema_path, &json_schema, check);
    check_or_write(&manifest_path, &manifest, check);
    ensure_absent(
        &root.join("packages/app-web/src/generated/agent-runtime-validators.ts"),
        check,
    );
    ensure_absent(
        &root.join("packages/app-web/src/generated/agent-runtime-service-codecs.ts"),
        check,
    );
}

fn ensure_no_bigint(source: &str) {
    if source
        .split(|character: char| !character.is_ascii_alphanumeric() && character != '_')
        .any(|token| token == "bigint")
    {
        panic!("Agent Runtime TypeScript wire contract must not contain bigint");
    }
}

fn codec_roots() -> &'static [CodecRoot] {
    &[
        CodecRoot {
            type_name: "AgentCommandEnvelope",
            function_stem: "AgentCommandEnvelope",
        },
        CodecRoot {
            type_name: "CreateAgentCommand",
            function_stem: "CreateAgentCommand",
        },
        CodecRoot {
            type_name: "ResumeAgentCommand",
            function_stem: "ResumeAgentCommand",
        },
        CodecRoot {
            type_name: "ForkAgentCommand",
            function_stem: "ForkAgentCommand",
        },
        CodecRoot {
            type_name: "AgentCommandReceipt",
            function_stem: "AgentCommandReceipt",
        },
        CodecRoot {
            type_name: "AgentSnapshot",
            function_stem: "AgentSnapshot",
        },
        CodecRoot {
            type_name: "AgentChange",
            function_stem: "AgentChange",
        },
        CodecRoot {
            type_name: "AgentChangePage",
            function_stem: "AgentChangePage",
        },
        CodecRoot {
            type_name: "AgentEffectInspection",
            function_stem: "AgentEffectInspection",
        },
        CodecRoot {
            type_name: "AgentSurfaceSnapshot",
            function_stem: "AgentSurfaceSnapshot",
        },
        CodecRoot {
            type_name: "ApplyBoundAgentSurface",
            function_stem: "ApplyBoundAgentSurface",
        },
        CodecRoot {
            type_name: "RevokeBoundAgentSurface",
            function_stem: "RevokeBoundAgentSurface",
        },
        CodecRoot {
            type_name: "AgentToolInvocation",
            function_stem: "AgentToolInvocation",
        },
        CodecRoot {
            type_name: "AgentHookInvocation",
            function_stem: "AgentHookInvocation",
        },
        CodecRoot {
            type_name: "AgentRuntimeOperationReceipt",
            function_stem: "AgentRuntimeOperationReceipt",
        },
        CodecRoot {
            type_name: "AgentRuntimeView",
            function_stem: "AgentRuntimeView",
        },
        CodecRoot {
            type_name: "AgentRuntimeUpdate",
            function_stem: "AgentRuntimeUpdate",
        },
        CodecRoot {
            type_name: "AgentRuntimeStreamFrame",
            function_stem: "AgentRuntimeStreamFrame",
        },
        CodecRoot {
            type_name: "AgentRuntimeContextProjection",
            function_stem: "AgentRuntimeContextProjection",
        },
        CodecRoot {
            type_name: "AgentRuntimeProjectionSchema",
            function_stem: "AgentRuntimeProjectionSchema",
        },
        CodecRoot {
            type_name: "AgentRuntimeContractSchema",
            function_stem: "AgentRuntimeContractSchema",
        },
    ]
}

fn merge_schema_definitions(target: &mut serde_json::Value, source: &serde_json::Value) {
    let target_definitions = target
        .get_mut("$defs")
        .and_then(serde_json::Value::as_object_mut)
        .expect("target schema must expose $defs");
    if let Some(source_definitions) = source.get("$defs").and_then(serde_json::Value::as_object) {
        for (name, definition) in source_definitions {
            target_definitions
                .entry(name.clone())
                .or_insert_with(|| definition.clone());
        }
    }
    let title = source
        .get("title")
        .and_then(serde_json::Value::as_str)
        .expect("source schema must expose title");
    target_definitions
        .entry(title.to_owned())
        .or_insert_with(|| {
            let mut root = source.clone();
            root.as_object_mut()
                .expect("source schema root must be object")
                .remove("$defs");
            root
        });
}

fn required_runtime_type_names() -> BTreeSet<String> {
    [
        "AgentRuntimeContractSchema",
        "AgentRuntimeProjectionSchema",
        "AgentRuntimeView",
        "AgentRuntimeUpdate",
        "AgentRuntimeStreamFrame",
        "AgentRuntimeSourceBindingEvidence",
        "AgentInteractionRequest",
        "AgentInteractionStatus",
        "AgentInteractionResolution",
        "AgentServiceApiSchema",
        "AgentServiceInstanceId",
        "CompleteAgentLiveAttachmentId",
        "AgentHostCallbackError",
        "RuntimeU64",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect()
}

fn ensure_required_declarations(declarations: &[String], required: &BTreeSet<String>) {
    let emitted = declarations
        .iter()
        .filter_map(|declaration| declaration_name(declaration))
        .collect::<BTreeSet<_>>();
    let missing = required
        .iter()
        .filter(|name| !emitted.contains(name.as_str()))
        .cloned()
        .collect::<Vec<_>>();
    if !missing.is_empty() {
        panic!(
            "Agent Runtime export closure omitted declarations: {}",
            missing.join(", ")
        );
    }
}

fn declaration_name(declaration: &str) -> Option<&str> {
    declaration.lines().find_map(|line| {
        let line = line.trim_start();
        let remainder = line
            .strip_prefix("export type ")
            .or_else(|| line.strip_prefix("export interface "))?;
        remainder
            .split(|character: char| !character.is_ascii_alphanumeric() && character != '_')
            .next()
            .filter(|name| !name.is_empty())
    })
}

fn exported_type_names(path: &Path) -> BTreeSet<String> {
    fs::read_to_string(path)
        .expect("read canonical backbone protocol TypeScript")
        .lines()
        .filter_map(|line| declaration_name(line).map(str::to_owned))
        .collect()
}

fn ensure_no_implicit_bindings() {
    let crates = Path::new(env!("CARGO_MANIFEST_DIR")).join("..");
    if let Some(path) = find_implicit_bindings(&crates) {
        panic!(
            "{} must not exist; TypeScript contracts are generated only through explicit workspace generators",
            path.display()
        );
    }
}

fn find_implicit_bindings(directory: &Path) -> Option<std::path::PathBuf> {
    for entry in fs::read_dir(directory).ok()? {
        let path = entry.ok()?.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|name| name == "bindings") {
                return Some(path);
            }
            if let Some(found) = find_implicit_bindings(&path) {
                return Some(found);
            }
        }
    }
    None
}

fn collect_typescript(directory: &Path, declarations: &mut Vec<String>) {
    for entry in fs::read_dir(directory).expect("read generated TypeScript directory") {
        let path = entry.expect("read generated entry").path();
        if path.is_dir() {
            collect_typescript(&path, declarations);
        } else if path.extension().is_some_and(|extension| extension == "ts") {
            let declaration = fs::read_to_string(path)
                .expect("read generated TypeScript")
                .lines()
                .filter(|line| !line.starts_with("// ") && !line.starts_with("import "))
                .map(str::trim_end)
                .collect::<Vec<_>>()
                .join("\n")
                .trim()
                .to_owned();
            if !declaration.is_empty() {
                declarations.push(declaration);
            }
        }
    }
}

fn check_or_write(path: &Path, expected: &str, check: bool) {
    if check {
        match fs::read_to_string(path) {
            Ok(actual) if actual == expected => {
                eprintln!("{} is up to date", path.display());
                return;
            }
            Ok(_) | Err(_) => {
                eprintln!(
                    "{} is out of date; regenerate during the S5 canonical artifact cut",
                    path.display()
                );
                std::process::exit(1);
            }
        }
    }
    fs::create_dir_all(path.parent().expect("generated parent")).expect("create generated parent");
    fs::write(path, expected).expect("write generated contract");
    eprintln!("wrote {}", path.display());
}

fn ensure_absent(path: &Path, check: bool) {
    if !path.exists() {
        return;
    }
    if check {
        eprintln!(
            "obsolete generated artifact still exists: {}",
            path.display()
        );
        std::process::exit(1);
    }
    fs::remove_file(path).expect("remove obsolete generated artifact");
    eprintln!("removed {}", path.display());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic(expected = "must not contain bigint")]
    fn bigint_is_rejected_from_runtime_wire_contract() {
        ensure_no_bigint("export type Revision = bigint;");
    }

    #[test]
    fn required_closure_covers_runtime_control_vocabulary() {
        let names = required_runtime_type_names();
        for required in [
            "AgentInteractionRequest",
            "AgentInteractionStatus",
            "AgentInteractionResolution",
            "AgentRuntimeUpdate",
        ] {
            assert!(names.contains(required), "missing {required}");
        }
    }

    #[test]
    #[should_panic(expected = "omitted declarations")]
    fn missing_runtime_declaration_is_generation_failure() {
        let declarations =
            vec!["export type AgentRuntimeView = { view_revision: string };".to_owned()];
        let required = ["AgentRuntimeView", "AgentInteractionRequest"]
            .into_iter()
            .map(str::to_owned)
            .collect();
        ensure_required_declarations(&declarations, &required);
    }
}
