use std::{env, fs, path::Path};

use agentdash_agent_runtime_contract::{
    ManagedRuntimeContractSchema, ManagedRuntimeProjectionSchema,
};
use schemars::schema_for;
use ts_rs::TS;

fn main() {
    let check = env::args().any(|argument| argument == "--check");
    ensure_no_implicit_bindings();
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let ts_path = root.join("packages/app-web/src/generated/agent-runtime-contracts.ts");
    let validators_path = root.join("packages/app-web/src/generated/agent-runtime-validators.ts");
    let schema_path = root.join("schemas/agent-runtime-contract.schema.json");
    let temp = tempfile::tempdir().expect("create generation directory");
    ManagedRuntimeContractSchema::export_all_to(temp.path())
        .expect("export Managed Runtime contract types");
    ManagedRuntimeProjectionSchema::export_all_to(temp.path())
        .expect("export Managed Runtime projection types");
    let mut declarations = Vec::new();
    collect_typescript(temp.path(), &mut declarations);
    declarations.sort();
    let typescript = format!(
        "// Generated by `cargo run -p agentdash-agent-runtime-contract --bin generate_agent_runtime_contracts`; do not edit.\n\n{}\n",
        declarations.join("\n\n")
    );
    ensure_no_bigint(&typescript);
    let json_schema = format!(
        "{}\n",
        serde_json::to_string_pretty(&schema_for!(ManagedRuntimeContractSchema))
            .expect("serialize Managed Runtime JSON Schema")
    );
    check_or_write(&ts_path, &typescript, check);
    check_or_write(&validators_path, MANAGED_RUNTIME_VALIDATORS, check);
    check_or_write(&schema_path, &json_schema, check);
}

fn ensure_no_bigint(source: &str) {
    if source
        .split(|character: char| !character.is_ascii_alphanumeric() && character != '_')
        .any(|token| token == "bigint")
    {
        panic!("Managed Runtime TypeScript wire contract must not contain bigint");
    }
}

const MANAGED_RUNTIME_VALIDATORS: &str = r#"// Generated by `cargo run -p agentdash-agent-runtime-contract --bin generate_agent_runtime_contracts`; do not edit.

import type {
  ManagedRuntimeChangePage,
  ManagedRuntimeProjectionSchema,
  ManagedRuntimeSnapshot,
} from "./agent-runtime-contracts";

export type ManagedRuntimeValidationResult<T> =
  | { ok: true; value: T }
  | { ok: false; field_path: string; expected: string };

function isRecord(value: unknown): value is Record<string, unknown> {
  return value != null && typeof value === "object" && !Array.isArray(value);
}

function isWireInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 0;
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

export function isManagedRuntimeSnapshot(value: unknown): value is ManagedRuntimeSnapshot {
  return isRecord(value)
    && isNonEmptyString(value.thread_id)
    && isWireInteger(value.revision)
    && isWireInteger(value.latest_change_sequence)
    && isWireInteger(value.captured_at_ms)
    && isNonEmptyString(value.lifecycle)
    && Array.isArray(value.turns)
    && Array.isArray(value.items)
    && Array.isArray(value.interactions)
    && Array.isArray(value.operations)
    && isNonEmptyString(value.authority)
    && isNonEmptyString(value.fidelity)
    && isRecord(value.command_availability);
}

export function isManagedRuntimeChangePage(value: unknown): value is ManagedRuntimeChangePage {
  return isRecord(value)
    && isNonEmptyString(value.thread_id)
    && Array.isArray(value.changes)
    && isWireInteger(value.next)
    && (value.gap === null || isRecord(value.gap));
}

export function isManagedRuntimeProjectionSchema(
  value: unknown,
): value is ManagedRuntimeProjectionSchema {
  return isRecord(value)
    && isManagedRuntimeSnapshot(value.snapshot)
    && isManagedRuntimeChangePage(value.change_page)
    && value.snapshot.thread_id === value.change_page.thread_id;
}

export function parseManagedRuntimeProjectionSchema(
  value: unknown,
): ManagedRuntimeValidationResult<ManagedRuntimeProjectionSchema> {
  if (!isRecord(value)) return { ok: false, field_path: "$", expected: "object" };
  if (!isManagedRuntimeSnapshot(value.snapshot)) {
    return { ok: false, field_path: "snapshot", expected: "ManagedRuntimeSnapshot" };
  }
  if (!isManagedRuntimeChangePage(value.change_page)) {
    return { ok: false, field_path: "change_page", expected: "ManagedRuntimeChangePage" };
  }
  if (value.snapshot.thread_id !== value.change_page.thread_id) {
    return { ok: false, field_path: "change_page.thread_id", expected: "snapshot thread_id" };
  }
  return { ok: true, value: value as ManagedRuntimeProjectionSchema };
}
"#;

fn ensure_no_implicit_bindings() {
    let crates = Path::new(env!("CARGO_MANIFEST_DIR")).join("..");
    if let Some(path) = find_implicit_bindings(&crates) {
        panic!(
            "{} must not exist; TypeScript contracts are generated only through explicit workspace generators",
            path.display()
        );
    }
}

fn find_implicit_bindings(directory: &Path) -> Option<std::path::PathBuf> {
    for entry in fs::read_dir(directory).ok()? {
        let path = entry.ok()?.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|name| name == "bindings") {
                return Some(path);
            }
            if let Some(found) = find_implicit_bindings(&path) {
                return Some(found);
            }
        }
    }
    None
}

fn collect_typescript(directory: &Path, declarations: &mut Vec<String>) {
    for entry in fs::read_dir(directory).expect("read generated TypeScript directory") {
        let path = entry.expect("read generated entry").path();
        if path.is_dir() {
            collect_typescript(&path, declarations);
        } else if path.extension().is_some_and(|extension| extension == "ts") {
            let declaration = fs::read_to_string(path)
                .expect("read generated TypeScript")
                .lines()
                .filter(|line| !line.starts_with("// ") && !line.starts_with("import "))
                .collect::<Vec<_>>()
                .join("\n")
                .trim()
                .to_owned();
            if !declaration.is_empty() {
                declarations.push(declaration);
            }
        }
    }
}

fn check_or_write(path: &Path, expected: &str, check: bool) {
    if check {
        match fs::read_to_string(path) {
            Ok(actual) if actual == expected => {
                eprintln!("{} is up to date", path.display());
                return;
            }
            Ok(_) | Err(_) => {
                eprintln!(
                    "{} is out of date; regenerate during the S5 canonical artifact cut",
                    path.display()
                );
                std::process::exit(1);
            }
        }
    }
    fs::create_dir_all(path.parent().expect("generated parent")).expect("create generated parent");
    fs::write(path, expected).expect("write generated contract");
    eprintln!("wrote {}", path.display());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic(expected = "must not contain bigint")]
    fn bigint_is_rejected_from_runtime_wire_contract() {
        ensure_no_bigint("export type Revision = bigint;");
    }
}
