use std::{env, fs, path::Path};

use agentdash_agent_runtime_contract::{RuntimeContractSchema, ToolProtocolProjection};
use schemars::schema_for;
use ts_rs::TS;

fn main() {
    let check = env::args().any(|argument| argument == "--check");
    ensure_no_implicit_bindings();
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let ts_path = root.join("packages/app-web/src/generated/agent-runtime-contracts.ts");
    let validator_path = root.join("packages/app-web/src/generated/agent-runtime-validators.ts");
    let schema_path = root.join("schemas/agent-runtime-contract.schema.json");

    let temp = tempfile::tempdir().expect("create generation directory");
    RuntimeContractSchema::export_all_to(temp.path()).expect("export runtime contract types");
    ToolProtocolProjection::export_all_to(temp.path())
        .expect("export tool protocol projection descriptor");
    let mut declarations = Vec::new();
    collect_typescript(temp.path(), &mut declarations);
    declarations.sort();
    let typescript = format!(
        "// Generated by `cargo run -p agentdash-agent-runtime-contract --bin generate_agent_runtime_contracts`; do not edit.\n\nimport type {{ ThreadItem }} from \"./backbone-protocol\";\n\n{}\n",
        declarations.join("\n\n")
    );

    let schema = schema_for!(RuntimeContractSchema);
    let json_schema = format!(
        "{}\n",
        serde_json::to_string_pretty(&schema).expect("serialize runtime JSON Schema")
    );

    check_or_write(&ts_path, &typescript, check);
    check_or_write(&validator_path, RUNTIME_VALIDATORS, check);
    check_or_write(&schema_path, &json_schema, check);
}

const RUNTIME_VALIDATORS: &str = r#"// Generated by `cargo run -p agentdash-agent-runtime-contract --bin generate_agent_runtime_contracts`; do not edit.

import type { RuntimeEventEnvelope, RuntimeTransientCoordinate } from "./agent-runtime-contracts";

export type RuntimeContractValidationResult<T> =
  | { ok: true; value: T }
  | { ok: false; field_path: string; expected: string };

function isRecord(value: unknown): value is Record<string, unknown> {
  return value != null && typeof value === "object" && !Array.isArray(value);
}

function isWireInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 0;
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

export function isGeneratedRuntimeTransientCoordinate(value: unknown): value is RuntimeTransientCoordinate {
  return isRecord(value)
    && isNonEmptyString(value.binding_id)
    && isWireInteger(value.stream_generation)
    && isWireInteger(value.sequence)
    && isNonEmptyString(value.event_id)
    && (value.turn_id === null || isNonEmptyString(value.turn_id));
}

export function isGeneratedRuntimeEventEnvelope(value: unknown): value is RuntimeEventEnvelope {
  if (!isRecord(value)) return false;
  return isNonEmptyString(value.thread_id)
    && isWireInteger(value.occurred_at_ms)
    && (value.sequence === null || isWireInteger(value.sequence))
    && (value.transient === null || isGeneratedRuntimeTransientCoordinate(value.transient))
    && ((value.sequence === null) !== (value.transient === null))
    && isWireInteger(value.revision)
    && isRecord(value.event)
    && isNonEmptyString(value.event.kind);
}

export function parseGeneratedRuntimeEventEnvelope(value: unknown): RuntimeContractValidationResult<RuntimeEventEnvelope> {
  if (!isRecord(value)) return { ok: false, field_path: "$", expected: "object" };
  if (!isNonEmptyString(value.thread_id)) return { ok: false, field_path: "thread_id", expected: "non-empty string" };
  if (!isWireInteger(value.occurred_at_ms)) return { ok: false, field_path: "occurred_at_ms", expected: "finite nonnegative safe integer" };
  if (!(value.sequence === null || isWireInteger(value.sequence))) return { ok: false, field_path: "sequence", expected: "finite nonnegative safe integer or null" };
  if (!(value.transient === null || isGeneratedRuntimeTransientCoordinate(value.transient))) return { ok: false, field_path: "transient", expected: "RuntimeTransientCoordinate or null" };
  if ((value.sequence === null) === (value.transient === null)) return { ok: false, field_path: "sequence/transient", expected: "exactly one durable sequence or transient coordinate" };
  if (!isWireInteger(value.revision)) return { ok: false, field_path: "revision", expected: "finite nonnegative safe integer" };
  if (!isRecord(value.event) || !isNonEmptyString(value.event.kind)) return { ok: false, field_path: "event.kind", expected: "non-empty string" };
  if (!isGeneratedRuntimeEventEnvelope(value)) return { ok: false, field_path: "$", expected: "RuntimeEventEnvelope" };
  return { ok: true, value };
}
"#;

fn ensure_no_implicit_bindings() {
    let crates = Path::new(env!("CARGO_MANIFEST_DIR")).join("..");
    if let Some(path) = find_implicit_bindings(&crates) {
        eprintln!(
            "{} must not exist; TypeScript contracts are generated only through explicit workspace generators",
            path.display()
        );
        std::process::exit(1);
    }
}

fn find_implicit_bindings(directory: &Path) -> Option<std::path::PathBuf> {
    for entry in fs::read_dir(directory).ok()? {
        let path = entry.ok()?.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|name| name == "bindings") {
                return Some(path);
            }
            if let Some(found) = find_implicit_bindings(&path) {
                return Some(found);
            }
        }
    }
    None
}

fn collect_typescript(directory: &Path, declarations: &mut Vec<String>) {
    for entry in fs::read_dir(directory).expect("read generated TypeScript directory") {
        let path = entry.expect("read generated entry").path();
        if path.is_dir() {
            collect_typescript(&path, declarations);
        } else if path.extension().is_some_and(|extension| extension == "ts") {
            let source = fs::read_to_string(path).expect("read generated TypeScript");
            let declaration = source
                .lines()
                .filter(|line| !line.starts_with("// ") && !line.starts_with("import "))
                .map(str::trim_end)
                .collect::<Vec<_>>()
                .join("\n")
                .trim()
                .to_string();
            if !declaration.is_empty() {
                declarations.push(declaration);
            }
        }
    }
}

fn check_or_write(path: &Path, expected: &str, check: bool) {
    if check {
        match fs::read_to_string(path) {
            Ok(actual) if actual == expected => {
                eprintln!("{} is up to date", path.display());
                return;
            }
            Ok(_) | Err(_) => {
                eprintln!(
                    "{} is out of date; run the Agent Runtime contract generator",
                    path.display()
                );
                std::process::exit(1);
            }
        }
    }

    fs::create_dir_all(path.parent().expect("generated parent")).expect("create generated parent");
    fs::write(path, expected).expect("write generated contract");
    eprintln!("wrote {}", path.display());
}
