export type {
  ExtensionBundleKindResponse,
  ExtensionBundleProjectionResponse,
  ExtensionCommandHandlerResponse,
  ExtensionCommandProjectionResponse,
  ExtensionFlagProjectionResponse,
  ExtensionFlagTypeResponse,
  ExtensionInstallationProjectionResponse,
  ExtensionInstalledAssetSourceResponse,
  ExtensionMessageRendererDeclarationResponse,
  ExtensionMessageRendererProjectionResponse,
  ExtensionPermissionAccessResponse,
  ExtensionPermissionDeclarationResponse,
  ExtensionPermissionProjectionResponse,
  ExtensionRuntimeActionKindResponse,
  ExtensionRuntimeActionProjectionResponse,
  ExtensionRuntimeInvocationOutputResponse,
  ExtensionRuntimeInvokeActionRequest,
  ExtensionRuntimeInvokeActionResponse,
  ExtensionRuntimeProjectionResponse,
  ExtensionRuntimeTraceResponse,
  ExtensionWorkspaceTabProjectionResponse,
  ExtensionWorkspaceTabRendererResponse,
} from "../generated/extension-runtime-contracts";
