export type {
  ExtensionBundleKindResponse,
  ExtensionBundleProjectionResponse,
  ExtensionCommandHandlerResponse,
  ExtensionCommandProjectionResponse,
  ExtensionDependencyDeclarationResponse,
  ExtensionDependencyProjectionResponse,
  ExtensionFlagProjectionResponse,
  ExtensionFlagTypeResponse,
  ExtensionInstallationProjectionResponse,
  ExtensionInstalledAssetSourceResponse,
  ExtensionMessageRendererDeclarationResponse,
  ExtensionMessageRendererProjectionResponse,
  ExtensionPermissionAccessResponse,
  ExtensionPermissionDeclarationResponse,
  ExtensionPermissionProjectionResponse,
  ExtensionProcessPermissionAccessResponse,
  ExtensionProtocolMethodProjectionResponse,
  ExtensionProtocolProjectionResponse,
  ExtensionRuntimeActionKindResponse,
  ExtensionRuntimeActionProjectionResponse,
  ExtensionRuntimeProjectionResponse,
  ExtensionWorkspaceTabProjectionResponse,
  ExtensionWorkspaceTabRendererResponse,
} from "../generated/extension-runtime-contracts";
