use std::collections::{BTreeMap, BTreeSet};

pub const GENERATED_HEADER: &[&str] = &[
    "// This file is generated by `cargo run -p agentdash-contracts --bin generate_contracts_ts`.",
    "// Do not edit manually.",
];

pub const COMMON_CONTRACTS_FILENAME: &str = "common-contracts.ts";
pub const COMMON_CONTRACTS_IMPORT_SOURCE: &str = "./common-contracts";
pub const JSON_VALUE_TYPE_NAME: &str = "JsonValue";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedTsFile {
    pub filename: String,
    pub contents: String,
    pub exported_types: BTreeSet<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DomainTypeDeclarations {
    pub filename: String,
    pub declarations: BTreeMap<String, String>,
}

#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct GeneratedFileSet {
    files: BTreeMap<String, GeneratedTsFile>,
}

impl GeneratedFileSet {
    pub fn iter(&self) -> impl Iterator<Item = &GeneratedTsFile> {
        self.files.values()
    }

    pub fn get(&self, filename: &str) -> Option<&GeneratedTsFile> {
        self.files.get(filename)
    }
}

pub fn render_generated_contracts(domains: Vec<DomainTypeDeclarations>) -> GeneratedFileSet {
    let mut upstream = BTreeMap::new();
    let mut files = BTreeMap::new();

    let common = render_common_json_value();
    files.insert(common.filename.clone(), common);

    for domain in domains {
        let rendered = render_domain_file(&domain.filename, domain.declarations, &upstream);
        let source = import_source_for_filename(&domain.filename);
        for name in &rendered.exported_types {
            upstream.insert(name.clone(), source.clone());
        }
        files.insert(rendered.filename.clone(), rendered);
    }

    GeneratedFileSet { files }
}

pub fn render_common_json_value() -> GeneratedTsFile {
    let mut lines = header_lines();
    lines.push(String::new());
    lines.push(
        "export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;"
            .to_string(),
    );
    lines.push(String::new());

    GeneratedTsFile {
        filename: COMMON_CONTRACTS_FILENAME.to_string(),
        contents: lines.join("\n"),
        exported_types: BTreeSet::from([JSON_VALUE_TYPE_NAME.to_string()]),
    }
}

pub fn render_domain_file(
    filename: &str,
    mut declarations: BTreeMap<String, String>,
    upstream: &BTreeMap<String, String>,
) -> GeneratedTsFile {
    declarations.remove(JSON_VALUE_TYPE_NAME);

    let mut stripped = Vec::new();
    for (type_name, source) in upstream {
        if declarations.remove(type_name).is_some() {
            stripped.push((type_name.clone(), source.clone()));
        }
    }

    let remaining_text = declarations
        .values()
        .cloned()
        .collect::<Vec<_>>()
        .join("\n");
    let dedup_imports = dedup_imports(&remaining_text, &stripped, upstream);

    let mut lines = header_lines();
    lines.push(String::new());

    let mut has_imports = false;
    if text_references_type(&remaining_text, JSON_VALUE_TYPE_NAME) {
        lines.push(format!(
            "import type {{ {JSON_VALUE_TYPE_NAME} }} from \"{COMMON_CONTRACTS_IMPORT_SOURCE}\";"
        ));
        has_imports = true;
    }

    for (source, names) in &dedup_imports {
        let joined = names.join(", ");
        lines.push(format!("import type {{ {joined} }} from \"{source}\";"));
        has_imports = true;
    }

    if has_imports {
        lines.push(String::new());
    }

    let exported_types = declarations.keys().cloned().collect();
    for declaration in declarations.values() {
        lines.push(declaration.clone());
        lines.push(String::new());
    }

    GeneratedTsFile {
        filename: filename.to_string(),
        contents: lines.join("\n"),
        exported_types,
    }
}

pub fn import_source_for_filename(filename: &str) -> String {
    let stem = filename.strip_suffix(".ts").unwrap_or(filename);
    format!("./{stem}")
}

fn dedup_imports(
    remaining_text: &str,
    stripped: &[(String, String)],
    upstream: &BTreeMap<String, String>,
) -> BTreeMap<String, Vec<String>> {
    let mut imports: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for (type_name, source) in stripped {
        if text_references_type(remaining_text, type_name) {
            imports
                .entry(source.clone())
                .or_default()
                .push(type_name.clone());
        }
    }

    for (type_name, source) in upstream {
        if stripped.iter().any(|(name, _)| name == type_name) {
            continue;
        }
        if text_references_type(remaining_text, type_name) {
            imports
                .entry(source.clone())
                .or_default()
                .push(type_name.clone());
        }
    }

    imports
}

fn header_lines() -> Vec<String> {
    GENERATED_HEADER
        .iter()
        .map(|line| (*line).to_string())
        .collect()
}

fn text_references_type(text: &str, name: &str) -> bool {
    text.split(|c: char| !c.is_ascii_alphanumeric() && c != '_')
        .any(|word| word == name)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn declarations(entries: &[(&str, &str)]) -> BTreeMap<String, String> {
        entries
            .iter()
            .map(|(name, declaration)| ((*name).to_string(), (*declaration).to_string()))
            .collect()
    }

    #[test]
    fn common_contract_file_has_generated_header_and_json_value_type() {
        let rendered = render_common_json_value();

        assert_eq!(rendered.filename, COMMON_CONTRACTS_FILENAME);
        assert!(rendered.contents.starts_with(
            "// This file is generated by `cargo run -p agentdash-contracts --bin generate_contracts_ts`.\n// Do not edit manually.\n"
        ));
        assert!(rendered.contents.contains("export type JsonValue ="));
        assert_eq!(
            rendered.exported_types,
            BTreeSet::from([JSON_VALUE_TYPE_NAME.to_string()])
        );
    }

    #[test]
    fn domain_rendering_deduplicates_upstream_declarations_and_imports_references() {
        let upstream =
            BTreeMap::from([("SharedRef".to_string(), "./shared-contracts".to_string())]);
        let rendered = render_domain_file(
            "domain-contracts.ts",
            declarations(&[
                ("LocalDto", "export type LocalDto = { shared: SharedRef };"),
                ("SharedRef", "export type SharedRef = { id: string };"),
            ]),
            &upstream,
        );

        assert!(
            rendered
                .contents
                .contains("import type { SharedRef } from \"./shared-contracts\";")
        );
        assert!(
            rendered
                .contents
                .contains("export type LocalDto = { shared: SharedRef };")
        );
        assert!(!rendered.contents.contains("export type SharedRef ="));
        assert_eq!(
            rendered.exported_types,
            BTreeSet::from(["LocalDto".to_string()])
        );
    }

    #[test]
    fn domain_rendering_omits_unused_dedup_imports() {
        let upstream =
            BTreeMap::from([("SharedRef".to_string(), "./shared-contracts".to_string())]);
        let rendered = render_domain_file(
            "domain-contracts.ts",
            declarations(&[
                ("LocalDto", "export type LocalDto = { id: string };"),
                ("SharedRef", "export type SharedRef = { id: string };"),
            ]),
            &upstream,
        );

        assert!(!rendered.contents.contains("import type"));
        assert!(
            rendered
                .contents
                .contains("export type LocalDto = { id: string };")
        );
        assert!(!rendered.contents.contains("export type SharedRef ="));
    }

    #[test]
    fn domain_rendering_imports_common_json_value_when_referenced() {
        let rendered = render_domain_file(
            "domain-contracts.ts",
            declarations(&[(
                "JsonBackedDto",
                "export type JsonBackedDto = { payload: JsonValue };",
            )]),
            &BTreeMap::new(),
        );

        assert!(
            rendered
                .contents
                .contains("import type { JsonValue } from \"./common-contracts\";")
        );
        assert!(
            rendered
                .contents
                .contains("export type JsonBackedDto = { payload: JsonValue };")
        );
    }

    #[test]
    fn rendered_file_set_registers_upstream_exports_between_domains() {
        let file_set = render_generated_contracts(vec![
            DomainTypeDeclarations {
                filename: "first-contracts.ts".to_string(),
                declarations: declarations(&[(
                    "SharedRef",
                    "export type SharedRef = { id: string };",
                )]),
            },
            DomainTypeDeclarations {
                filename: "second-contracts.ts".to_string(),
                declarations: declarations(&[(
                    "SecondDto",
                    "export type SecondDto = { shared: SharedRef };",
                )]),
            },
        ]);

        let second = file_set.get("second-contracts.ts").expect("second file");
        assert!(
            second
                .contents
                .contains("import type { SharedRef } from \"./first-contracts\";")
        );
        assert!(file_set.get(COMMON_CONTRACTS_FILENAME).is_some());
    }
}
