#[path = "agent/run_mailbox.rs"]
pub mod agent_run_mailbox;
#[path = "system/auth.rs"]
pub mod auth;
pub mod backend;
#[path = "surface/canvas.rs"]
pub mod canvas;
pub mod common_response;
#[path = "system/companion.rs"]
pub mod companion;
pub mod context;
pub mod contract_generation;
pub mod desktop_release;
#[path = "extension/management.rs"]
pub mod extension_management;
#[path = "extension/package.rs"]
pub mod extension_package;
#[path = "extension/runtime.rs"]
pub mod extension_runtime;
#[path = "extension/external_marketplace.rs"]
pub mod external_marketplace;
#[path = "integration/llm_provider.rs"]
pub mod llm_provider;
#[path = "integration/mcp_preset.rs"]
pub mod mcp_preset;
pub mod project;
#[path = "agent/project_agent.rs"]
pub mod project_agent;
#[path = "runtime/routine.rs"]
pub mod routine;
#[path = "runtime/session.rs"]
pub mod session;
#[path = "system/settings.rs"]
pub mod settings;
#[path = "integration/shared_library.rs"]
pub mod shared_library;
#[path = "integration/skill_asset.rs"]
pub mod skill_asset;
pub mod story;
pub mod task;
#[path = "surface/vfs.rs"]
pub mod vfs;
#[path = "runtime/workflow.rs"]
pub mod workflow;
pub mod workspace;
#[path = "surface/workspace_module.rs"]
pub mod workspace_module;
