// Generated by `cargo run -p agentdash-agent-service-api --bin generate_agent_service_api`; do not edit.

import type {
  AgentAppliedEffectOutcome as AgentAppliedEffectOutcomeWire,
  AgentChange as AgentChangeWire,
  AgentChangePage as AgentChangePageWire,
  AgentCommandEnvelope as AgentCommandEnvelopeWire,
  AgentCommandMeta as AgentCommandMetaWire,
  AgentCommandReceipt as AgentCommandReceiptWire,
  AgentEffectInspection as AgentEffectInspectionWire,
  AgentHookInvocation as AgentHookInvocationWire,
  AgentHostCallbackBinding as AgentHostCallbackBindingWire,
  AgentHostCallbackMeta as AgentHostCallbackMetaWire,
  AgentServiceU64,
  AgentSnapshot as AgentSnapshotWire,
  AgentSnapshotSource as AgentSnapshotSourceWire,
  AgentSurfaceSnapshot as AgentSurfaceSnapshotWire,
  AgentToolInvocation as AgentToolInvocationWire,
  AppliedAgentCommandReceipt as AppliedAgentCommandReceiptWire,
  AppliedAgentSurface as AppliedAgentSurfaceWire,
  ApplyBoundAgentSurface as ApplyBoundAgentSurfaceWire,
  BoundAgentSurface as BoundAgentSurfaceWire,
  CreateAgentCommand as CreateAgentCommandWire,
  ForkAgentCommand as ForkAgentCommandWire,
  ForkAgentReceipt as ForkAgentReceiptWire,
  ResumeAgentCommand as ResumeAgentCommandWire,
  RevokeBoundAgentSurface as RevokeBoundAgentSurfaceWire,
} from "./agent-service-api";

export type DecodeAgentServiceU64<T> =
  T extends AgentServiceU64 ? bigint
    : T extends readonly (infer Item)[] ? DecodeAgentServiceU64<Item>[]
      : T extends object ? { [Key in keyof T]: DecodeAgentServiceU64<T[Key]> }
        : T;

export type AgentChange = DecodeAgentServiceU64<AgentChangeWire>;
export type AgentChangePage = DecodeAgentServiceU64<AgentChangePageWire>;
export type AgentCommandEnvelope = DecodeAgentServiceU64<AgentCommandEnvelopeWire>;
export type AgentCommandReceipt = DecodeAgentServiceU64<AgentCommandReceiptWire>;
export type AgentEffectInspection = DecodeAgentServiceU64<AgentEffectInspectionWire>;
export type AgentHookInvocation = DecodeAgentServiceU64<AgentHookInvocationWire>;
export type AgentSnapshot = DecodeAgentServiceU64<AgentSnapshotWire>;
export type AgentSurfaceSnapshot = DecodeAgentServiceU64<AgentSurfaceSnapshotWire>;
export type AgentToolInvocation = DecodeAgentServiceU64<AgentToolInvocationWire>;
export type ApplyBoundAgentSurface = DecodeAgentServiceU64<ApplyBoundAgentSurfaceWire>;
export type CreateAgentCommand = DecodeAgentServiceU64<CreateAgentCommandWire>;
export type ForkAgentCommand = DecodeAgentServiceU64<ForkAgentCommandWire>;
export type ForkAgentReceipt = DecodeAgentServiceU64<ForkAgentReceiptWire>;
export type ResumeAgentCommand = DecodeAgentServiceU64<ResumeAgentCommandWire>;
export type RevokeBoundAgentSurface = DecodeAgentServiceU64<RevokeBoundAgentSurfaceWire>;

const CANONICAL_U64 = /^(0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$/;
const U64_MAX = 18_446_744_073_709_551_615n;

export class AgentServiceContractDecodeError extends Error {
  readonly fieldPath: string;
  readonly expected: string;

  constructor(
    fieldPath: string,
    expected = "canonical unsigned-decimal u64 string",
  ) {
    super(`${fieldPath}: expected ${expected}`);
    this.fieldPath = fieldPath;
    this.expected = expected;
  }
}

function record(value: unknown, path: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new AgentServiceContractDecodeError(path, "object");
  }
  return value as Record<string, unknown>;
}

function array(value: unknown, path: string): unknown[] {
  if (!Array.isArray(value)) {
    throw new AgentServiceContractDecodeError(path, "array");
  }
  return value;
}

export function decodeAgentServiceU64(value: unknown, path = "$"): bigint {
  if (typeof value !== "string" || !CANONICAL_U64.test(value)) {
    throw new AgentServiceContractDecodeError(path);
  }
  const decoded = BigInt(value);
  if (decoded > U64_MAX) {
    throw new AgentServiceContractDecodeError(path, "u64 range");
  }
  return decoded;
}

export function encodeAgentServiceU64(
  value: bigint,
  path = "$",
): AgentServiceU64 {
  if (value < 0n || value > U64_MAX) {
    throw new AgentServiceContractDecodeError(path, "u64 bigint");
  }
  return value.toString(10) as AgentServiceU64;
}

type Direction = "decode" | "encode";

function scalar(value: unknown, path: string, direction: Direction): unknown {
  return direction === "decode"
    ? decodeAgentServiceU64(value, path)
    : encodeAgentServiceU64(value as bigint, path);
}

function optionalScalar(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  return value === null ? null : scalar(value, path, direction);
}

function transformCommandMeta(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const meta = record(value, path);
  return {
    ...meta,
    binding_generation: scalar(
      meta.binding_generation,
      `${path}.binding_generation`,
      direction,
    ),
    expected_snapshot_revision: optionalScalar(
      meta.expected_snapshot_revision,
      `${path}.expected_snapshot_revision`,
      direction,
    ),
  };
}

function transformSnapshotSource(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const source = record(value, path);
  return {
    ...source,
    observed_at_ms: scalar(source.observed_at_ms, `${path}.observed_at_ms`, direction),
  };
}

function transformSurfacePayload(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const payload = record(value, path);
  return payload.kind === "hook"
    ? {
        ...payload,
        deadline_ms: scalar(payload.deadline_ms, `${path}.deadline_ms`, direction),
      }
    : payload;
}

function transformSurfaceRequirements(
  value: unknown,
  path: string,
  direction: Direction,
): unknown[] {
  return array(value, path).map((entry, index) => {
    const requirement = record(entry, `${path}[${index}]`);
    return {
      ...requirement,
      payload: transformSurfacePayload(
        requirement.payload,
        `${path}[${index}].payload`,
        direction,
      ),
    };
  });
}

function transformAgentSurfaceSnapshot(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const surface = record(value, path);
  return {
    ...surface,
    revision: scalar(surface.revision, `${path}.revision`, direction),
    requirements: transformSurfaceRequirements(
      surface.requirements,
      `${path}.requirements`,
      direction,
    ),
  };
}

function transformBoundSurface(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const surface = record(value, path);
  return {
    ...surface,
    revision: scalar(surface.revision, `${path}.revision`, direction),
    contributions: array(surface.contributions, `${path}.contributions`).map(
      (entry, index) => {
        const contribution = record(entry, `${path}.contributions[${index}]`);
        return {
          ...contribution,
          payload: transformSurfacePayload(
            contribution.payload,
            `${path}.contributions[${index}].payload`,
            direction,
          ),
        };
      },
    ),
  };
}

function transformAppliedSurface(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const surface = record(value, path);
  return {
    ...surface,
    revision: scalar(surface.revision, `${path}.revision`, direction),
  };
}

function transformCallbackBinding(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const binding = record(value, path);
  return {
    ...binding,
    binding_generation: scalar(
      binding.binding_generation,
      `${path}.binding_generation`,
      direction,
    ),
    default_deadline_ms: scalar(
      binding.default_deadline_ms,
      `${path}.default_deadline_ms`,
      direction,
    ),
  };
}

function transformCallbackMeta(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const meta = record(value, path);
  return {
    ...meta,
    binding_generation: scalar(
      meta.binding_generation,
      `${path}.binding_generation`,
      direction,
    ),
    deadline_at_ms: scalar(meta.deadline_at_ms, `${path}.deadline_at_ms`, direction),
  };
}

function transformInitialContext(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  if (value === null) return null;
  const context = record(value, path);
  return {
    ...context,
    schema_version: scalar(context.schema_version, `${path}.schema_version`, direction),
  };
}

function transformAppliedCommandReceipt(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const receipt = record(value, path);
  return {
    ...receipt,
    snapshot_revision: optionalScalar(
      receipt.snapshot_revision,
      `${path}.snapshot_revision`,
      direction,
    ),
  };
}

function transformCommandReceipt(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const receipt = record(value, path);
  return {
    ...receipt,
    snapshot_revision: optionalScalar(
      receipt.snapshot_revision,
      `${path}.snapshot_revision`,
      direction,
    ),
  };
}

function transformAppliedOutcome(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const outcome = record(value, path);
  switch (outcome.kind) {
    case "create":
    case "resume":
    case "command":
    case "surface_revoke":
      return {
        ...outcome,
        receipt: transformAppliedCommandReceipt(
          outcome.receipt,
          `${path}.receipt`,
          direction,
        ),
      };
    case "surface_apply": {
      const receipt = record(outcome.receipt, `${path}.receipt`);
      return {
        ...outcome,
        receipt: {
          ...receipt,
          applied: transformAppliedSurface(
            receipt.applied,
            `${path}.receipt.applied`,
            direction,
          ),
        },
      };
    }
    case "fork":
      return outcome;
    default:
      throw new AgentServiceContractDecodeError(`${path}.kind`, "known applied outcome");
  }
}

function transformEffectInspection(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const inspection = record(value, path);
  const state = record(inspection.state, `${path}.state`);
  return {
    ...inspection,
    state:
      state.kind === "applied"
        ? {
            ...state,
            outcome: transformAppliedOutcome(
              state.outcome,
              `${path}.state.outcome`,
              direction,
            ),
          }
        : state,
  };
}

function transformChange(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const change = record(value, path);
  const payload = record(change.payload, `${path}.payload`);
  let transformedPayload: unknown = payload;
  if (payload.kind === "thread_name_changed") {
    transformedPayload = {
      ...payload,
      source_info: transformSnapshotSource(
        payload.source_info,
        `${path}.payload.source_info`,
        direction,
      ),
    };
  } else if (payload.kind === "surface_applied") {
    transformedPayload = {
      ...payload,
      applied: transformAppliedSurface(
        payload.applied,
        `${path}.payload.applied`,
        direction,
      ),
    };
  }
  return {
    ...change,
    occurred_at_ms: scalar(change.occurred_at_ms, `${path}.occurred_at_ms`, direction),
    payload: transformedPayload,
  };
}

function transformSnapshot(
  value: unknown,
  path: string,
  direction: Direction,
): unknown {
  const snapshot = record(value, path);
  const threadName =
    snapshot.thread_name === null
      ? null
      : (() => {
          const source = record(snapshot.thread_name, `${path}.thread_name`);
          return {
            ...source,
            source_info: transformSnapshotSource(
              source.source_info,
              `${path}.thread_name.source_info`,
              direction,
            ),
          };
        })();
  return {
    ...snapshot,
    revision: scalar(snapshot.revision, `${path}.revision`, direction),
    source_info: transformSnapshotSource(
      snapshot.source_info,
      `${path}.source_info`,
      direction,
    ),
    thread_name: threadName,
    applied_surface:
      snapshot.applied_surface === null
        ? null
        : transformAppliedSurface(
            snapshot.applied_surface,
            `${path}.applied_surface`,
            direction,
          ),
  };
}

export function decodeAgentCommandEnvelope(value: unknown): AgentCommandEnvelope {
  const envelope = record(value, "$");
  return {
    ...envelope,
    meta: transformCommandMeta(envelope.meta, "$.meta", "decode"),
  } as AgentCommandEnvelope;
}

export function encodeAgentCommandEnvelope(
  value: AgentCommandEnvelope,
): AgentCommandEnvelopeWire {
  return {
    ...value,
    meta: transformCommandMeta(value.meta, "$.meta", "encode"),
  } as AgentCommandEnvelopeWire;
}

export function decodeCreateAgentCommand(value: unknown): CreateAgentCommand {
  const command = record(value, "$");
  return {
    ...command,
    meta: transformCommandMeta(command.meta, "$.meta", "decode"),
    initial_context: transformInitialContext(
      command.initial_context,
      "$.initial_context",
      "decode",
    ),
  } as CreateAgentCommand;
}

export function encodeCreateAgentCommand(value: CreateAgentCommand): CreateAgentCommandWire {
  return {
    ...value,
    meta: transformCommandMeta(value.meta, "$.meta", "encode"),
    initial_context: transformInitialContext(
      value.initial_context,
      "$.initial_context",
      "encode",
    ),
  } as CreateAgentCommandWire;
}

export function decodeResumeAgentCommand(value: unknown): ResumeAgentCommand {
  const command = record(value, "$");
  return {
    ...command,
    meta: transformCommandMeta(command.meta, "$.meta", "decode"),
  } as ResumeAgentCommand;
}

export function encodeResumeAgentCommand(value: ResumeAgentCommand): ResumeAgentCommandWire {
  return {
    ...value,
    meta: transformCommandMeta(value.meta, "$.meta", "encode"),
  } as ResumeAgentCommandWire;
}

export function decodeForkAgentCommand(value: unknown): ForkAgentCommand {
  const command = record(value, "$");
  return {
    ...command,
    meta: transformCommandMeta(command.meta, "$.meta", "decode"),
  } as ForkAgentCommand;
}

export function encodeForkAgentCommand(value: ForkAgentCommand): ForkAgentCommandWire {
  return {
    ...value,
    meta: transformCommandMeta(value.meta, "$.meta", "encode"),
  } as ForkAgentCommandWire;
}

export function decodeAgentCommandReceipt(value: unknown): AgentCommandReceipt {
  return transformCommandReceipt(value, "$", "decode") as AgentCommandReceipt;
}

export function encodeAgentCommandReceipt(
  value: AgentCommandReceipt,
): AgentCommandReceiptWire {
  return transformCommandReceipt(value, "$", "encode") as AgentCommandReceiptWire;
}

export function decodeForkAgentReceipt(value: unknown): ForkAgentReceipt {
  return record(value, "$") as ForkAgentReceipt;
}

export function encodeForkAgentReceipt(value: ForkAgentReceipt): ForkAgentReceiptWire {
  return value as ForkAgentReceiptWire;
}

export function decodeAgentSnapshot(value: unknown): AgentSnapshot {
  return transformSnapshot(value, "$", "decode") as AgentSnapshot;
}

export function encodeAgentSnapshot(value: AgentSnapshot): AgentSnapshotWire {
  return transformSnapshot(value, "$", "encode") as AgentSnapshotWire;
}

export function decodeAgentChange(value: unknown): AgentChange {
  return transformChange(value, "$", "decode") as AgentChange;
}

export function encodeAgentChange(value: AgentChange): AgentChangeWire {
  return transformChange(value, "$", "encode") as AgentChangeWire;
}

export function decodeAgentChangePage(value: unknown): AgentChangePage {
  const page = record(value, "$");
  return {
    ...page,
    changes: array(page.changes, "$.changes").map((change, index) =>
      transformChange(change, `$.changes[${index}]`, "decode")
    ),
  } as AgentChangePage;
}

export function encodeAgentChangePage(value: AgentChangePage): AgentChangePageWire {
  return {
    ...value,
    changes: value.changes.map((change, index) =>
      transformChange(change, `$.changes[${index}]`, "encode")
    ),
  } as AgentChangePageWire;
}

export function decodeAgentEffectInspection(value: unknown): AgentEffectInspection {
  return transformEffectInspection(value, "$", "decode") as AgentEffectInspection;
}

export function encodeAgentEffectInspection(
  value: AgentEffectInspection,
): AgentEffectInspectionWire {
  return transformEffectInspection(value, "$", "encode") as AgentEffectInspectionWire;
}

export function decodeAgentSurfaceSnapshot(value: unknown): AgentSurfaceSnapshot {
  return transformAgentSurfaceSnapshot(value, "$", "decode") as AgentSurfaceSnapshot;
}

export function encodeAgentSurfaceSnapshot(
  value: AgentSurfaceSnapshot,
): AgentSurfaceSnapshotWire {
  return transformAgentSurfaceSnapshot(value, "$", "encode") as AgentSurfaceSnapshotWire;
}

export function decodeApplyBoundAgentSurface(value: unknown): ApplyBoundAgentSurface {
  const command = record(value, "$");
  return {
    ...command,
    bound_surface: transformBoundSurface(command.bound_surface, "$.bound_surface", "decode"),
    callbacks: transformCallbackBinding(command.callbacks, "$.callbacks", "decode"),
  } as ApplyBoundAgentSurface;
}

export function encodeApplyBoundAgentSurface(
  value: ApplyBoundAgentSurface,
): ApplyBoundAgentSurfaceWire {
  return {
    ...value,
    bound_surface: transformBoundSurface(value.bound_surface, "$.bound_surface", "encode"),
    callbacks: transformCallbackBinding(value.callbacks, "$.callbacks", "encode"),
  } as ApplyBoundAgentSurfaceWire;
}

export function decodeRevokeBoundAgentSurface(value: unknown): RevokeBoundAgentSurface {
  const command = record(value, "$");
  return {
    ...command,
    binding_generation: scalar(
      command.binding_generation,
      "$.binding_generation",
      "decode",
    ),
    expected_revision: scalar(command.expected_revision, "$.expected_revision", "decode"),
  } as RevokeBoundAgentSurface;
}

export function encodeRevokeBoundAgentSurface(
  value: RevokeBoundAgentSurface,
): RevokeBoundAgentSurfaceWire {
  return {
    ...value,
    binding_generation: scalar(
      value.binding_generation,
      "$.binding_generation",
      "encode",
    ),
    expected_revision: scalar(value.expected_revision, "$.expected_revision", "encode"),
  } as RevokeBoundAgentSurfaceWire;
}

export function decodeAgentToolInvocation(value: unknown): AgentToolInvocation {
  const invocation = record(value, "$");
  return {
    ...invocation,
    meta: transformCallbackMeta(invocation.meta, "$.meta", "decode"),
  } as AgentToolInvocation;
}

export function encodeAgentToolInvocation(value: AgentToolInvocation): AgentToolInvocationWire {
  return {
    ...value,
    meta: transformCallbackMeta(value.meta, "$.meta", "encode"),
  } as AgentToolInvocationWire;
}

export function decodeAgentHookInvocation(value: unknown): AgentHookInvocation {
  const invocation = record(value, "$");
  return {
    ...invocation,
    meta: transformCallbackMeta(invocation.meta, "$.meta", "decode"),
  } as AgentHookInvocation;
}

export function encodeAgentHookInvocation(value: AgentHookInvocation): AgentHookInvocationWire {
  return {
    ...value,
    meta: transformCallbackMeta(value.meta, "$.meta", "encode"),
  } as AgentHookInvocationWire;
}

export type AgentCommandMeta = DecodeAgentServiceU64<AgentCommandMetaWire>;
export type AgentSnapshotSource = DecodeAgentServiceU64<AgentSnapshotSourceWire>;
export type AgentHostCallbackBinding =
  DecodeAgentServiceU64<AgentHostCallbackBindingWire>;
export type AgentHostCallbackMeta = DecodeAgentServiceU64<AgentHostCallbackMetaWire>;
export type AppliedAgentCommandReceipt =
  DecodeAgentServiceU64<AppliedAgentCommandReceiptWire>;
export type AgentAppliedEffectOutcome =
  DecodeAgentServiceU64<AgentAppliedEffectOutcomeWire>;
export type AppliedAgentSurface = DecodeAgentServiceU64<AppliedAgentSurfaceWire>;
export type BoundAgentSurface = DecodeAgentServiceU64<BoundAgentSurfaceWire>;
