use std::{collections::BTreeSet, env, fs, path::Path};

use agentdash_agent_service_api::{
    AgentHostCallbackError, AgentServiceApiSchema, AgentServiceInstanceId,
};
use schemars::schema_for;
use ts_rs::TS;

fn main() {
    let check = env::args().any(|argument| argument == "--check");
    ensure_no_implicit_bindings();
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let ts_path = root.join("packages/app-web/src/generated/agent-service-api.ts");
    let schema_path = root.join("schemas/agent-service-api.schema.json");
    let temp = tempfile::tempdir().expect("create Complete Agent Service generation directory");
    AgentServiceApiSchema::export_all_to(temp.path())
        .expect("export Complete Agent Service API types");
    AgentServiceInstanceId::export_all_to(temp.path())
        .expect("export Complete Agent Service routing identity");
    AgentHostCallbackError::export_all_to(temp.path())
        .expect("export Complete Agent Host callback error");
    let mut declarations = Vec::new();
    collect_typescript(temp.path(), &mut declarations);
    declarations.sort();
    ensure_required_declarations(&declarations, &required_service_type_names());
    let typescript = format!(
        "// Generated by `cargo run -p agentdash-agent-service-api --bin generate_agent_service_api`; do not edit.\n\n{}\n",
        declarations.join("\n\n")
    );
    ensure_no_bigint(&typescript);
    let json_schema = format!(
        "{}\n",
        serde_json::to_string_pretty(&schema_for!(AgentServiceApiSchema))
            .expect("serialize Complete Agent Service JSON Schema")
    );
    check_or_write(&ts_path, &typescript, check);
    check_or_write(&schema_path, &json_schema, check);
}

fn required_service_type_names() -> BTreeSet<String> {
    [
        "AgentServiceApiSchema",
        "AgentServiceDescriptor",
        "CreateAgentCommand",
        "ResumeAgentCommand",
        "ForkAgentCommand",
        "AgentCommandEnvelope",
        "AgentCommandReceipt",
        "ForkAgentReceipt",
        "AgentReadQuery",
        "AgentSnapshot",
        "AgentChangesQuery",
        "AgentChangePage",
        "AgentEffectInspection",
        "AgentSurfaceSnapshot",
        "BoundAgentSurface",
        "AppliedAgentSurface",
        "ApplyBoundAgentSurface",
        "RevokeBoundAgentSurface",
        "AgentToolInvocation",
        "AgentToolResult",
        "AgentHookInvocation",
        "AgentHookDecision",
        "AgentHostCallbackError",
        "AgentServiceInstanceId",
        "AgentServiceError",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect()
}

fn ensure_required_declarations(declarations: &[String], required: &BTreeSet<String>) {
    let emitted = declarations
        .iter()
        .filter_map(|declaration| declaration_name(declaration))
        .collect::<BTreeSet<_>>();
    let missing = required
        .iter()
        .filter(|name| !emitted.contains(name.as_str()))
        .cloned()
        .collect::<Vec<_>>();
    if !missing.is_empty() {
        panic!(
            "Complete Agent Service export closure omitted declarations: {}",
            missing.join(", ")
        );
    }
}

fn ensure_no_bigint(source: &str) {
    if source
        .split(|character: char| !character.is_ascii_alphanumeric() && character != '_')
        .any(|token| token == "bigint")
    {
        panic!("Complete Agent Service TypeScript wire contract must not contain bigint");
    }
}

fn declaration_name(declaration: &str) -> Option<&str> {
    declaration.lines().find_map(|line| {
        let line = line.trim_start();
        let remainder = line
            .strip_prefix("export type ")
            .or_else(|| line.strip_prefix("export interface "))?;
        remainder
            .split(|character: char| !character.is_ascii_alphanumeric() && character != '_')
            .next()
            .filter(|name| !name.is_empty())
    })
}

fn ensure_no_implicit_bindings() {
    let crates = Path::new(env!("CARGO_MANIFEST_DIR")).join("..");
    if let Some(path) = find_implicit_bindings(&crates) {
        panic!(
            "{} must not exist; TypeScript contracts are generated only through explicit workspace generators",
            path.display()
        );
    }
}

fn find_implicit_bindings(directory: &Path) -> Option<std::path::PathBuf> {
    for entry in fs::read_dir(directory).ok()? {
        let path = entry.ok()?.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|name| name == "bindings") {
                return Some(path);
            }
            if let Some(found) = find_implicit_bindings(&path) {
                return Some(found);
            }
        }
    }
    None
}

fn collect_typescript(directory: &Path, declarations: &mut Vec<String>) {
    for entry in fs::read_dir(directory).expect("read generated TypeScript directory") {
        let path = entry.expect("read generated entry").path();
        if path.is_dir() {
            collect_typescript(&path, declarations);
        } else if path.extension().is_some_and(|extension| extension == "ts") {
            let declaration = fs::read_to_string(path)
                .expect("read generated TypeScript")
                .lines()
                .filter(|line| !line.starts_with("// ") && !line.starts_with("import "))
                .collect::<Vec<_>>()
                .join("\n")
                .trim()
                .to_owned();
            if !declaration.is_empty() {
                declarations.push(declaration);
            }
        }
    }
}

fn check_or_write(path: &Path, expected: &str, check: bool) {
    if check {
        match fs::read_to_string(path) {
            Ok(actual) if actual == expected => {
                eprintln!("{} is up to date", path.display());
                return;
            }
            Ok(_) | Err(_) => {
                eprintln!(
                    "{} is out of date; regenerate during the S5 canonical artifact cut",
                    path.display()
                );
                std::process::exit(1);
            }
        }
    }
    fs::create_dir_all(path.parent().expect("generated parent")).expect("create generated parent");
    fs::write(path, expected).expect("write generated Complete Agent Service contract");
    eprintln!("wrote {}", path.display());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn required_closure_covers_commands_state_surface_and_callbacks() {
        let names = required_service_type_names();
        for required in [
            "AgentCommandEnvelope",
            "AgentSnapshot",
            "AgentChangePage",
            "BoundAgentSurface",
            "AgentToolInvocation",
            "AgentHookInvocation",
        ] {
            assert!(names.contains(required), "missing Service-owned {required}");
        }
    }

    #[test]
    #[should_panic(expected = "omitted declarations")]
    fn missing_required_service_declaration_is_a_generation_failure() {
        let declarations = vec!["export type AgentSnapshot = { revision: number };".to_owned()];
        let required = ["AgentSnapshot", "AgentCommandEnvelope"]
            .into_iter()
            .map(str::to_owned)
            .collect();
        ensure_required_declarations(&declarations, &required);
    }

    #[test]
    #[should_panic(expected = "must not contain bigint")]
    fn bigint_is_rejected_from_service_wire_contract() {
        ensure_no_bigint("export type Revision = bigint;");
    }
}
