use std::{env, fs, path::Path};

use agentdash_agent_runtime_wire::RuntimeWireEnvelope;
use schemars::schema_for;
use ts_rs::TS;

fn main() {
    let check = env::args().any(|argument| argument == "--check");
    ensure_no_implicit_bindings();
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let ts_path = root.join("packages/app-web/src/generated/agent-runtime-wire.ts");
    let schema_path = root.join("schemas/agent-runtime-wire.schema.json");
    let temp = tempfile::tempdir().expect("create generation directory");
    RuntimeWireEnvelope::export_all_to(temp.path()).expect("export Runtime Wire types");
    let mut declarations = Vec::new();
    collect_typescript(temp.path(), &mut declarations);
    declarations.sort();
    let typescript = format!(
        "// Generated by `cargo run -p agentdash-agent-runtime-wire --bin generate_agent_runtime_wire`; do not edit.\n\n{}\n",
        declarations.join("\n\n")
    );
    let json_schema = format!(
        "{}\n",
        serde_json::to_string_pretty(&schema_for!(RuntimeWireEnvelope))
            .expect("serialize Runtime Wire JSON Schema")
    );
    check_or_write(&ts_path, &typescript, check);
    check_or_write(&schema_path, &json_schema, check);
}

fn ensure_no_implicit_bindings() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("bindings");
    if path.exists() {
        eprintln!(
            "{} must not exist; Runtime Wire contracts are generated only through the explicit generator",
            path.display()
        );
        std::process::exit(1);
    }
}

fn collect_typescript(directory: &Path, declarations: &mut Vec<String>) {
    for entry in fs::read_dir(directory).expect("read generated TypeScript directory") {
        let path = entry.expect("read generated entry").path();
        if path.is_dir() {
            collect_typescript(&path, declarations);
        } else if path.extension().is_some_and(|extension| extension == "ts") {
            let declaration = fs::read_to_string(path)
                .expect("read generated TypeScript")
                .lines()
                .filter(|line| !line.starts_with("// ") && !line.starts_with("import "))
                .collect::<Vec<_>>()
                .join("\n")
                .trim()
                .to_string();
            if !declaration.is_empty() {
                declarations.push(declaration);
            }
        }
    }
}

fn check_or_write(path: &Path, expected: &str, check: bool) {
    if check {
        match fs::read_to_string(path) {
            Ok(actual) if actual == expected => {
                eprintln!("{} is up to date", path.display());
                return;
            }
            Ok(_) | Err(_) => {
                eprintln!(
                    "{} is out of date; run the Runtime Wire generator",
                    path.display()
                );
                std::process::exit(1);
            }
        }
    }
    fs::create_dir_all(path.parent().expect("generated parent")).expect("create generated parent");
    fs::write(path, expected).expect("write generated contract");
    eprintln!("wrote {}", path.display());
}
