use std::{collections::BTreeSet, env, fs, path::Path};

use agentdash_agent_runtime_wire::RuntimeWireEnvelope;
use schemars::schema_for;
use ts_rs::TS;

fn main() {
    let check = env::args().any(|argument| argument == "--check");
    ensure_no_implicit_bindings();
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let ts_path = root.join("packages/app-web/src/generated/agent-runtime-wire.ts");
    let contract_ts_path = root.join("packages/app-web/src/generated/agent-runtime-contracts.ts");
    let schema_path = root.join("schemas/agent-runtime-wire.schema.json");
    let temp = tempfile::tempdir().expect("create generation directory");
    RuntimeWireEnvelope::export_all_to(temp.path()).expect("export Runtime Wire types");
    let mut declarations = Vec::new();
    collect_typescript(temp.path(), &mut declarations);

    let contract_source = fs::read_to_string(&contract_ts_path).unwrap_or_else(|error| {
        panic!(
            "read canonical Runtime contract bindings at {}: {error}; run the contract generator first",
            contract_ts_path.display()
        )
    });
    let contract_names = exported_type_names(&contract_source);
    let wire_owned = wire_owned_type_names();
    if let Some(collision) = wire_owned
        .iter()
        .find(|name| contract_names.contains(*name))
    {
        panic!("Runtime Wire type `{collision}` collides with the canonical Runtime contract");
    }

    declarations.retain(|declaration| {
        declaration_name(declaration).is_some_and(|name| wire_owned.contains(name))
    });
    declarations.sort();
    let wire_source = declarations.join("\n\n");
    let imports = referenced_contract_names(&wire_source, &contract_names);
    let import = if imports.is_empty() {
        String::new()
    } else {
        format!(
            "import type {{ {} }} from \"./agent-runtime-contracts\";\n\n",
            imports.into_iter().collect::<Vec<_>>().join(", ")
        )
    };
    let typescript = format!(
        "// Generated by `cargo run -p agentdash-agent-runtime-wire --bin generate_agent_runtime_wire`; do not edit.\n\n{import}{wire_source}\n",
    );
    let json_schema = format!(
        "{}\n",
        serde_json::to_string_pretty(&schema_for!(RuntimeWireEnvelope))
            .expect("serialize Runtime Wire JSON Schema")
    );
    check_or_write(&ts_path, &typescript, check);
    check_or_write(&schema_path, &json_schema, check);
}

fn wire_owned_type_names() -> BTreeSet<String> {
    [
        "RuntimeProtocolViolation",
        "RuntimeWireAck",
        "RuntimeWireChangesResult",
        "RuntimeWireEnvelope",
        "RuntimeWireExecuteResult",
        "RuntimeWireFrame",
        "RuntimeWireFrameId",
        "RuntimeWireNotification",
        "RuntimeWireReadResult",
        "RuntimeWireRequest",
        "RuntimeWireResponse",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect()
}

fn exported_type_names(source: &str) -> BTreeSet<String> {
    source
        .lines()
        .filter_map(declaration_name)
        .map(str::to_owned)
        .collect()
}

fn declaration_name(declaration: &str) -> Option<&str> {
    let declaration = declaration.trim_start();
    let remainder = declaration
        .strip_prefix("export type ")
        .or_else(|| declaration.strip_prefix("export interface "))?;
    remainder
        .split(|character: char| !character.is_ascii_alphanumeric() && character != '_')
        .next()
        .filter(|name| !name.is_empty())
}

fn referenced_contract_names(source: &str, contract_names: &BTreeSet<String>) -> BTreeSet<String> {
    source
        .split(|character: char| !character.is_ascii_alphanumeric() && character != '_')
        .filter(|token| contract_names.contains(*token))
        .map(str::to_owned)
        .collect()
}

fn ensure_no_implicit_bindings() {
    let crates = Path::new(env!("CARGO_MANIFEST_DIR")).join("..");
    if let Some(path) = find_implicit_bindings(&crates) {
        panic!(
            "{} must not exist; TypeScript contracts are generated only through explicit workspace generators",
            path.display()
        );
    }
}

fn find_implicit_bindings(directory: &Path) -> Option<std::path::PathBuf> {
    for entry in fs::read_dir(directory).ok()? {
        let path = entry.ok()?.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|name| name == "bindings") {
                return Some(path);
            }
            if let Some(found) = find_implicit_bindings(&path) {
                return Some(found);
            }
        }
    }
    None
}

fn collect_typescript(directory: &Path, declarations: &mut Vec<String>) {
    for entry in fs::read_dir(directory).expect("read generated TypeScript directory") {
        let path = entry.expect("read generated entry").path();
        if path.is_dir() {
            collect_typescript(&path, declarations);
        } else if path.extension().is_some_and(|extension| extension == "ts") {
            let declaration = fs::read_to_string(path)
                .expect("read generated TypeScript")
                .lines()
                .filter(|line| !line.starts_with("// ") && !line.starts_with("import "))
                .collect::<Vec<_>>()
                .join("\n")
                .trim()
                .to_owned();
            if !declaration.is_empty() {
                declarations.push(declaration);
            }
        }
    }
}

fn check_or_write(path: &Path, expected: &str, check: bool) {
    if check {
        match fs::read_to_string(path) {
            Ok(actual) if actual == expected => {
                eprintln!("{} is up to date", path.display());
                return;
            }
            Ok(_) | Err(_) => {
                eprintln!(
                    "{} is out of date; regenerate during the S5 canonical artifact cut",
                    path.display()
                );
                std::process::exit(1);
            }
        }
    }
    fs::create_dir_all(path.parent().expect("generated parent")).expect("create generated parent");
    fs::write(path, expected).expect("write generated contract");
    eprintln!("wrote {}", path.display());
}
