// Generated by `cargo run -p agentdash-agent-runtime-wire --bin generate_agent_runtime_wire`; do not edit.

import type {
  RuntimeWireEnvelope as RuntimeWireEnvelopeRaw,
  RuntimeWireFrame as RuntimeWireFrameRaw,
  RuntimeWireU64,
} from "./agent-runtime-wire";

export type DecodeRuntimeWireU64<T> =
  T extends RuntimeWireU64 ? bigint
    : T extends readonly (infer Item)[] ? DecodeRuntimeWireU64<Item>[]
      : T extends object ? { [Key in keyof T]: DecodeRuntimeWireU64<T[Key]> }
        : T;

export type RuntimeWireEnvelope = DecodeRuntimeWireU64<RuntimeWireEnvelopeRaw>;
export type RuntimeWireFrame = DecodeRuntimeWireU64<RuntimeWireFrameRaw>;

const CANONICAL_U64 = /^(0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$/;
const U64_MAX = 18_446_744_073_709_551_615n;

export class RuntimeWireDecodeError extends Error {
  readonly fieldPath: string;
  readonly expected: string;

  constructor(
    fieldPath: string,
    expected = "canonical unsigned-decimal u64 string",
  ) {
    super(`${fieldPath}: expected ${expected}`);
    this.fieldPath = fieldPath;
    this.expected = expected;
  }
}

function record(value: unknown, path: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new RuntimeWireDecodeError(path, "object");
  }
  return value as Record<string, unknown>;
}

export function decodeRuntimeWireU64(value: unknown, path = "$"): bigint {
  if (typeof value !== "string" || !CANONICAL_U64.test(value)) {
    throw new RuntimeWireDecodeError(path);
  }
  const decoded = BigInt(value);
  if (decoded > U64_MAX) {
    throw new RuntimeWireDecodeError(path, "u64 range");
  }
  return decoded;
}

export function encodeRuntimeWireU64(value: bigint, path = "$"): RuntimeWireU64 {
  if (value < 0n || value > U64_MAX) {
    throw new RuntimeWireDecodeError(path, "u64 bigint");
  }
  return value.toString(10) as RuntimeWireU64;
}

function decodeFrame(value: unknown, path: string): RuntimeWireFrame {
  const frame = record(value, path);
  const payload = record(frame.payload, `${path}.payload`);
  switch (frame.kind) {
    case "request":
    case "notification":
      if (
        frame.kind === "notification"
        && payload.kind === "heartbeat"
      ) {
        const heartbeat = record(payload.payload, `${path}.payload.payload`);
        return {
          ...frame,
          payload: {
            ...payload,
            payload: {
              ...heartbeat,
              last_received_frame_id: decodeRuntimeWireU64(
                heartbeat.last_received_frame_id,
                `${path}.payload.payload.last_received_frame_id`,
              ),
            },
          },
        } as RuntimeWireFrame;
      }
      return frame as RuntimeWireFrame;
    case "response":
      return {
        ...frame,
        payload: {
          ...payload,
          request_frame_id: decodeRuntimeWireU64(
            payload.request_frame_id,
            `${path}.payload.request_frame_id`,
          ),
        },
      } as RuntimeWireFrame;
    case "ack":
      return {
        ...frame,
        payload: {
          ...payload,
          through_frame_id: decodeRuntimeWireU64(
            payload.through_frame_id,
            `${path}.payload.through_frame_id`,
          ),
        },
      } as RuntimeWireFrame;
    default:
      throw new RuntimeWireDecodeError(`${path}.kind`, "known Runtime Wire frame");
  }
}

function encodeFrame(value: RuntimeWireFrame, path: string): RuntimeWireFrameRaw {
  const frame = value as unknown as Record<string, unknown>;
  const payload = record(frame.payload, `${path}.payload`);
  switch (frame.kind) {
    case "request":
    case "notification":
      if (
        frame.kind === "notification"
        && payload.kind === "heartbeat"
      ) {
        const heartbeat = record(payload.payload, `${path}.payload.payload`);
        return {
          ...frame,
          payload: {
            ...payload,
            payload: {
              ...heartbeat,
              last_received_frame_id: encodeRuntimeWireU64(
                heartbeat.last_received_frame_id as bigint,
                `${path}.payload.payload.last_received_frame_id`,
              ),
            },
          },
        } as RuntimeWireFrameRaw;
      }
      return frame as RuntimeWireFrameRaw;
    case "response":
      return {
        ...frame,
        payload: {
          ...payload,
          request_frame_id: encodeRuntimeWireU64(
            payload.request_frame_id as bigint,
            `${path}.payload.request_frame_id`,
          ),
        },
      } as RuntimeWireFrameRaw;
    case "ack":
      return {
        ...frame,
        payload: {
          ...payload,
          through_frame_id: encodeRuntimeWireU64(
            payload.through_frame_id as bigint,
            `${path}.payload.through_frame_id`,
          ),
        },
      } as RuntimeWireFrameRaw;
    default:
      throw new RuntimeWireDecodeError(`${path}.kind`, "known Runtime Wire frame");
  }
}

export function decodeRuntimeWireEnvelope(value: unknown): RuntimeWireEnvelope {
  const envelope = record(value, "$");
  return {
    ...envelope,
    frame_id: decodeRuntimeWireU64(envelope.frame_id, "$.frame_id"),
    frame: decodeFrame(envelope.frame, "$.frame"),
  } as RuntimeWireEnvelope;
}

export function encodeRuntimeWireEnvelope(
  value: RuntimeWireEnvelope,
): RuntimeWireEnvelopeRaw {
  return {
    ...value,
    frame_id: encodeRuntimeWireU64(value.frame_id, "$.frame_id"),
    frame: encodeFrame(value.frame, "$.frame"),
  } as RuntimeWireEnvelopeRaw;
}
