use std::{collections::BTreeMap, env, fs, path::PathBuf};

use agentdash_agent_protocol::BackboneEnvelope;
use ts_rs::TS;

fn main() {
    let check = env::args().any(|arg| arg == "--check");
    let out: PathBuf = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../packages/app-web/src/generated/backbone-protocol.ts");

    fs::create_dir_all(out.parent().expect("generated dir")).expect("create generated dir");

    let tmp_dir = tempfile::tempdir().expect("create temp dir");
    BackboneEnvelope::export_all_to(tmp_dir.path()).expect("export all types");

    let mut declarations: BTreeMap<String, String> = BTreeMap::new();

    collect_ts_files(tmp_dir.path(), &mut declarations);
    let uses_json_value = declarations.remove("JsonValue").is_some();

    let mut lines = Vec::new();
    lines.push(
        "// This file is generated by `cargo run -p agentdash-agent-protocol --bin generate_backbone_protocol_ts`."
            .to_string(),
    );
    lines.push("// Do not edit manually.".to_string());
    lines.push(String::new());
    if uses_json_value {
        lines.push("import type { JsonValue } from \"./common-contracts\";".to_string());
        lines.push(String::new());
    }

    for decl in declarations.values() {
        lines.push(decl.clone());
        lines.push(String::new());
    }

    let output = lines.join("\n");

    if check {
        match fs::read_to_string(&out) {
            Ok(existing) if existing == output => {
                eprintln!("{} is up to date", out.display());
                return;
            }
            Ok(_) => {
                eprintln!(
                    "{} is out of date; run `cargo run -p agentdash-agent-protocol --bin generate_backbone_protocol_ts`",
                    out.display()
                );
                std::process::exit(1);
            }
            Err(error) => {
                eprintln!("failed to read {}: {error}", out.display());
                std::process::exit(1);
            }
        }
    }

    fs::write(&out, output).expect("write generated TS");

    eprintln!("Wrote {} ({} types)", out.display(), declarations.len());
}

fn collect_ts_files(dir: &std::path::Path, out: &mut BTreeMap<String, String>) {
    for entry in fs::read_dir(dir).expect("read dir") {
        let entry = entry.expect("read entry");
        let path = entry.path();
        if path.is_dir() {
            collect_ts_files(&path, out);
        } else if path.extension().is_some_and(|ext| ext == "ts") {
            let content = fs::read_to_string(&path).expect("read ts file");
            let stem = path
                .file_stem()
                .expect("file stem")
                .to_string_lossy()
                .to_string();

            let mut decl_lines = Vec::new();
            for line in content.lines() {
                if line.starts_with("// ") || line.starts_with("import ") {
                    continue;
                }
                if line.is_empty() && decl_lines.is_empty() {
                    continue;
                }
                decl_lines.push(line.trim_end().to_string());
            }

            while decl_lines.last().is_some_and(|l| l.is_empty()) {
                decl_lines.pop();
            }

            if !decl_lines.is_empty() {
                out.insert(stem, decl_lines.join("\n"));
            }
        }
    }
}
