use std::{fs, path::PathBuf};

use agentdash_acp_meta::{AgentDashEventV1, AgentDashMetaV1, AgentDashSourceV1, AgentDashTraceV1};
use ts_rs::TS;

fn main() {
    // Keep this path stable for the frontend to import.
    let out: PathBuf = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../frontend/src/generated/agentdash-acp-meta.ts");

    fs::create_dir_all(out.parent().expect("generated dir")).expect("create generated dir");

    // Write a single TS module. This keeps frontend imports stable and avoids relying on
    // ts-rs export path conventions across environments.
    fn export_decl(decl: String) -> String {
        if decl.starts_with("type ") || decl.starts_with("interface ") {
            format!("export {decl}")
        } else {
            decl
        }
    }

    let decls = [
        export_decl(AgentDashSourceV1::decl()),
        export_decl(AgentDashEventV1::decl()),
        export_decl(AgentDashTraceV1::decl()),
        export_decl(AgentDashMetaV1::decl()),
    ]
    .join("\n\n");

    let content = format!(
        "{}\n\n{}\n\n{}\n",
        "// This file is generated by `cargo run -p agentdash-acp-meta --bin generate_agentdash_acp_meta_ts`.",
        "export type JsonValue = unknown;",
        decls
    );
    fs::write(&out, content).expect("write generated TS");
}

